### ISSUE TITLE
Migration Failure Updating from Craft 2 -> Craft 3 version

### ISSUE THREAD

**Issue by mikestecker** [engram-design/SuperTable#122]
### Description

Migration failed updating from Craft 2 -> Craft 3

### Steps to reproduce

1. Updated Craft site from 2 -> 3
2. Installed Supertable from composer command line
3. Saw the migration procedure notification, clicked "Finish Up" to continue

### Additional info

- Plugin version: 2.0
- Craft version: Craft 3 RC9

Here's the error:
```
Error: Class 'verbb\supertable\migrations\Craft' not found

Migration: verbb\supertable\migrations\m180210_000000_migrate_content_tables

Output:

Exception: Class 'verbb\supertable\migrations\Craft' not found (/Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/verbb/super-table/src/migrations/m180210_000000_migrate_content_tables.php:23)
#0 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/db/Migration.php(44): verbb\supertable\migrations\m180210_000000_migrate_content_tables->safeUp()
#1 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/db/MigrationManager.php(250): craft\db\Migration->up(true)
#2 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/db/MigrationManager.php(166): craft\db\MigrationManager->migrateUp(Object(verbb\supertable\migrations\m180210_000000_migrate_content_tables))
#3 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/services/Updates.php(229): craft\db\MigrationManager->up()
#4 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/controllers/UpdaterController.php(211): craft\services\Updates->runMigrations(Array)
#5 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#6 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('migrate', Array)
#9 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#10 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/web/Application.php(241): yii\base\Module->runAction('updater/migrate', Array)
#11 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/web/Application.php(556): craft\web\Application->runAction('updater/migrate')
#12 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/web/Application.php(182): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#13 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#14 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/web/index.php(42): yii\base\Application->run()
#15 /Users/mikestecker/.composer/vendor/laravel/valet/server.php(133): require('/Users/mikestec...')
#16 {main}
```

**Comment by engram-design** [comment]
@mikestecker The latest commit should fix this. Can you give it a go by either:

- Downloading the repo and replacing the `src` folder
- Run composer require `verbb/super-table:dev-craft-3`.

**Comment by mikestecker** [comment]
@engram-design oops! Looks like another problem now after pulling that update:

```

One of Super Table’s migrations failed.

Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP INDEX craf_supertableconte_24_sectioncalltoactionbut_elementI_local_fk; check that it exists
The SQL being executed was: DROP INDEX craf_supertableconte_24_sectioncalltoactionbut_elementI_local_fk ON craft_supertablecontent_24_sectioncalltoactionbutton

Migration: verbb\supertable\migrations\m180210_000000_migrate_content_tables

Output:

Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP INDEX craf_supertableconte_24_sectioncalltoactionbut_elementI_local_fk; check that it exists
The SQL being executed was: DROP INDEX craf_supertableconte_24_sectioncalltoactionbut_elementI_local_fk ON craft_supertablecontent_24_sectioncalltoactionbutton (/Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/yiisoft/yii2/db/Schema.php:595)
#0 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/yiisoft/yii2/db/Command.php(1004): yii\db\Schema->convertException(Object(PDOException), 'DROP INDEX `cra...')
#1 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/helpers/MigrationHelper.php(677): yii\db\Command->execute()
#2 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/helpers/MigrationHelper.php(624): craft\helpers\MigrationHelper::dropIndex('{{%supertableco...', Array, false, NULL)
#3 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/helpers/MigrationHelper.php(162): craft\helpers\MigrationHelper::dropAllIndexesOnTable('{{%supertableco...', NULL)
#4 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/verbb/super-table/src/migrations/m180210_000000_migrate_content_tables.php(39): craft\helpers\MigrationHelper::renameTable('{{%supertableco...', '{{%stc_24_secti...')
#5 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/db/Migration.php(44): verbb\supertable\migrations\m180210_000000_migrate_content_tables->safeUp()
#6 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/db/MigrationManager.php(250): craft\db\Migration->up(true)
#7 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/db/MigrationManager.php(166): craft\db\MigrationManager->migrateUp(Object(verbb\supertable\migrations\m180210_000000_migrate_content_tables))
#8 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/services/Updates.php(229): craft\db\MigrationManager->up()
#9 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/controllers/UpdaterController.php(211): craft\services\Updates->runMigrations(Array)
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('migrate', Array)
#14 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/web/Application.php(241): yii\base\Module->runAction('updater/migrate', Array)
#16 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/web/Application.php(556): craft\web\Application->runAction('updater/migrate')
#17 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/craftcms/cms/src/web/Application.php(182): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/mikestecker/Documents/Projects/Website/acd-website-craft/web/index.php(42): yii\base\Application->run()
#20 /Users/mikestecker/.composer/vendor/laravel/valet/server.php(133): require('/Users/mikestec...')
#21 {main}
```

**Comment by engram-design** [comment]
@mikestecker This would be due to our renaming of the content tables for Super Table's content. This change was made to prevent issues like the one you're getting right now - but its still an issue for Craft 2 sites when renaming the table.

If you can, are you able to manually rename the database table from `craft_supertablecontent_*` to `craft_stc_*`? Or, if you refresh the migration, it should potentially skip to rename the next table.

**Comment by mikestecker** [comment]
Renaming the tables manually worked. Thanks!
