### ISSUE TITLE
Unknown Method - When adding a product to a cart with Craft Commerce.

### ISSUE THREAD

**Issue by mrksmts** [engram-design/SuperTable#175]
### Description

When adding something to a shopping cart Craft throws the following error.
_Calling unknown method: verbb\supertable\elements\SuperTableBlockElement::all()_

Tried this both with a custom template and the Craft Commerce example templates.

### Steps to reproduce

1. Go to product page
2. Click add to cart

### Additional info

- Plugin version: 2.0.7
- Craft version: 3.0.13.2
- Craft Commerce: 2.0.0-beta.6

```
yii\base\UnknownMethodException: Calling unknown method: verbb\supertable\elements\SuperTableBlockElement::all() in /var/www/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/base/Element.php(823): yii\base\Component->__call('all', Array)
#1 /var/www/vendor/verbb/super-table/src/fields/SuperTableField.php(394): craft\base\Element->__call('all', Array)
#2 /var/www/vendor/craftcms/cms/src/base/Element.php(1591): verbb\supertable\fields\SuperTableField->serializeValue(Object(verbb\supertable\elements\SuperTableBlockElement), Object(craft\commerce\elements\Product))
#3 /var/www/vendor/craftcms/commerce/src/elements/Variant.php(344): craft\base\Element->getSerializedFieldValues()
#4 /var/www/vendor/craftcms/commerce/src/models/LineItem.php(395): craft\commerce\elements\Variant->getSnapshot()
#5 /var/www/vendor/craftcms/commerce/src/services/LineItems.php(283): craft\commerce\models\LineItem->populateFromPurchasable(Object(craft\commerce\elements\Variant))
#6 /var/www/vendor/craftcms/commerce/src/services/LineItems.php(143): craft\commerce\services\LineItems->createLineItem(183, 93, Array, 1, '')
#7 /var/www/vendor/craftcms/commerce/src/controllers/CartController.php(154): craft\commerce\services\LineItems->resolveLineItem(183, 93, Array, 1, '')
#8 [internal function]: craft\commerce\controllers\CartController->actionUpdateCart()
#9 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('update-cart', Array)
#12 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('update-cart', Array)
#13 /var/www/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('commerce/cart/u...', Array)
#14 /var/www/vendor/craftcms/cms/src/web/Application.php(530): craft\web\Application->runAction('commerce/cart/u...', Array)
#15 /var/www/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /var/www/public_html/index.php(22): yii\base\Application->run()
#18 {main}
```

**Comment by mrksmts** [comment]
I've fixed it for now, by adding the missing function `all()` 

```
public function all() {
     return [];
}
```

**Comment by engram-design** [comment]
I probably need to know a little more about your setup. You've got a Super Table field attached to a product? What sort of ST field is it?

**Comment by mrksmts** [comment]
@engram-design Yes the ST field is attached to a product.

**Comment by engram-design** [comment]
Attached to the product, or to the variant? A static ST field or some other layout?

**Comment by mrksmts** [comment]
@engram-design It is attached to the product as a static ST field. The product has no variants. 

If you want I am available on the craftcms slack channel under the same username as on github.

**Comment by cornernote** [comment]
I am getting the same issue with ST attached to the variant

**Comment by engram-design** [comment]
The all function isn't missing, it shouldn't be required, as it should be querying super table blocks. I'm actually struggling to reproduce this.

Happy to chat on Slack if its still an issue (handle: `crawf`)

**Comment by engram-design** [comment]
@mrksmts Managed to fix this by updating their composer install
