### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by janhendrickx** [engram-design/SuperTable#176]
### Description
I purchased a pro version of Craft, created a user and suddenly the dashboard page went down. I get an error "Trying to get property of non-object" when I login (so on the /dashboard page when logged in). For some reason I am able to go to other pages.
I disabled superTable and all was well again (but I've used it quite a lot so that's not an option :-) )

### Steps to reproduce

1. Upgrade solo to Pro
2. Create user group
3. Create user
4. Keep on working in the CP
5. Suddenly Boom; broken dashboard

### Additional info

- Plugin version: 2.07
- Craft version: Just updated to 3.0.14 (but it was there in the previous version too, I hoped an update would clear the error)

## stacktrace:
yii\base\ErrorException: Trying to get property of non-object in /data/sites/web/moowbe9579/vendor/verbb/super-table/src/fields/SuperTableField.php:484
Stack trace:
#0 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/data/sites/web...', 484)
#1 /data/sites/web/moowbe9579/vendor/verbb/super-table/src/fields/SuperTableField.php(484): craft\web\ErrorHandler->handleError(8, 'Trying to get p...', '/data/sites/web...', 484, Array)
#2 /data/sites/web/moowbe9579/vendor/twig/twig/lib/Twig/Extension/Core.php(1605): verbb\supertable\fields\SuperTableField->getInputHtml(Array, NULL)
#3 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(verbb\supertable\fields\SuperTableField), 'getInputHtml', Array, 'method', false, false)
#4 /data/sites/web/moowbe9579/storage/runtime/compiled_templates/80/80815ca54a1d5dd7cee8c012b3d9a96af5797d872741dda51bacdc9b17c341c9.php(83): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(verbb\supertable\fields\SuperTableField), 'getInputHtml', Array, 'method')
#5 /data/sites/web/moowbe9579/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_c8b2696caed7f0861b82a4ffd45c006f71a04afea386091289cf6b42b0c7af21->doDisplay(Array, Array)
#6 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#7 /data/sites/web/moowbe9579/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#8 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#9 /data/sites/web/moowbe9579/storage/runtime/compiled_templates/07/077012142072122002b2ef64b57b7d664275139c9eae4a955a3075dc201096d1.php(70): craft\web\twig\Template->display(Array)
#10 /data/sites/web/moowbe9579/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_458d1a3f1914f894b576d63203c548dd87698fe7d63688938d46cef38f4b7571->doDisplay(Array, Array)
#11 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#12 /data/sites/web/moowbe9579/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#13 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#14 /data/sites/web/moowbe9579/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#15 /data/sites/web/moowbe9579/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#16 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/web/View.php(330): Twig_Environment->render('_components/wid...', Array)
#17 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/widgets/QuickPost.php(178): craft\web\View->renderTemplate('_components/wid...', Array)
#18 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/controllers/DashboardController.php(506): craft\widgets\QuickPost->getBodyHtml()
#19 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/controllers/DashboardController.php(98): craft\controllers\DashboardController->_getWidgetInfo(Object(craft\widgets\QuickPost))
#20 [internal function]: craft\controllers\DashboardController->actionIndex()
#21 /data/sites/web/moowbe9579/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /data/sites/web/moowbe9579/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#23 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('index', Array)
#24 /data/sites/web/moowbe9579/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#25 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('dashboard/index', Array)
#26 /data/sites/web/moowbe9579/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#27 /data/sites/web/moowbe9579/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#28 /data/sites/web/moowbe9579/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#29 /data/sites/web/moowbe9579/www/index.php(21): yii\base\Application->run()
#30 {main}

**Comment by janhendrickx** [comment]
Nevermind, seems to be a problem in Craft itself since I changed some settings and now I get an error on a different plugin so Craft seems to be doing something wrong somewhere :-)
