### ISSUE TITLE
Schematic import does not work

### ISSUE THREAD

**Issue by jon-heller** [engram-design/SuperTable#179]
### Description

When attempting to import Super Table fields using the Schematic plugin, we receive the error:

```
- Saving verbb\supertable\fields\SuperTableField chartTest
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: verbb\supertable\models\SuperTableBlockTypeModel::handle'

in /var/www/html/vendor/yiisoft/yii2/base/Component.php:154

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php(208): yii\base\Component->__get('handle')
#1 /var/www/html/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php(477): yii\helpers\BaseArrayHelper::getValue(Object(verbb\supertable\models\SuperTableBlockTypeModel), 'handle')
#2 /var/www/html/vendor/nerds-and-company/schematic/src/Mappers/ModelMapper.php(55): yii\helpers\BaseArrayHelper::index(Array, 'handle')
#3 /var/www/html/vendor/verbb/super-table/src/integrations/schematic/converters/fields/SuperTableSchematic.php(33): NerdsAndCompany\Schematic\Mappers\ModelMapper->import(Array, Array, Array)
#4 /var/www/html/vendor/nerds-and-company/schematic/src/Mappers/ModelMapper.php(68): verbb\supertable\integrations\schematic\converters\fields\SuperTableSchematic->saveRecord(Object(verbb\supertable\fields\SuperTableField), Array)
#5 /var/www/html/vendor/nerds-and-company/schematic/src/Controllers/ImportController.php(88): NerdsAndCompany\Schematic\Mappers\ModelMapper->import(Array, Array)
#6 /var/www/html/vendor/nerds-and-company/schematic/src/Controllers/ImportController.php(49): NerdsAndCompany\Schematic\Controllers\ImportController->importFromYaml(Array)
#7 [internal function]: NerdsAndCompany\Schematic\Controllers\ImportController->actionIndex()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('schematic/impor...', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('schematic/impor...', Array)
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /var/www/html/craft(22): yii\base\Application->run()
#16 {main}
```

### Steps to reproduce

1. Create a new Craft install
2. Install and enable Super Table and Schematic plugins
3. Either create a new Super Table field, export using Schematic, then delete the field OR use the attached schema.yml file
4. Import schema.yml

[schema.yml.txt](https://github.com/verbb/super-table/files/2201985/schema.yml.txt)

### Additional info

- Plugin version: 2.0.7
- Craft version: 3.0.15

**Comment by jon-heller** [comment]
After some testing we found that this is the same issue encountered in https://github.com/verbb/super-table/pull/168, and can also be fixed by using that PR

**Comment by roelvanhintum** [comment]
This is still an issue. Hard to debug so far.
