### ISSUE TITLE
Cant add or edit fields

### ISSUE THREAD

**Issue by jamielaughton** [engram-design/SuperTable#201]
### Description
After the latest Craft update I cannot add a field or edit any type field. When i do im presented with a twig error:

"Twig Runtime Error – Twig_Error_Runtime
Variable "blockTypes" does not exist."

in /vendor/craftcms/cms/src/templates/_components/fieldtypes/Matrix/settings.html at line 12

*See full error stack in comment of this issue.*

Im posting this bug here because if i dissable the super-table plugin i am able to add and edit fleds as normal. 

***Note: it was only after the latest Craft CMS update (3.0.23.1) that this started happening***

### Steps to reproduce

1. to to /admin/settings/fields
2. Try to add new field or edit existing

### Additional info

- Plugin version:2.0.8
- Craft version: 3.0.23.1

**Comment by jamielaughton** [comment]
`Twig_Error_Runtime: Variable "blockTypes" does not exist. in /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/templates/_components/fieldtypes/Matrix/settings.html:12
Stack trace:
#0 /Users/jamie/Documents/repos/spacecentre/public_html/storage/runtime/compiled_templates/fb/fb036a49a4c40e3c0e7e64dfd62322628c6a8f4dfab12887bf344ccf3d423c7e.php(44): __TwigTemplate_a3e43fb4272ab5f18eba67afd45d6f25f06cba908ba50e73edb28ddc68c54076->{closure}()
#1 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_a3e43fb4272ab5f18eba67afd45d6f25f06cba908ba50e73edb28ddc68c54076->doDisplay(Array, Array)
#2 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#4 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#5 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#6 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#7 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('_components/fie...', Array)
#8 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/verbb/super-table/src/services/SuperTableMatrixService.php(125): craft\web\View->renderTemplate('_components/fie...', Array)
#9 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/verbb/super-table/src/fields/SuperTableField.php(740): verbb\supertable\services\SuperTableMatrixService->getMatrixSettingsHtml(Object(craft\fields\Matrix))
#10 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/verbb/super-table/src/fields/SuperTableField.php(267): verbb\supertable\fields\SuperTableField->_getFieldOptionsForConfigurator()
#11 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/fields/Matrix.php(762): verbb\supertable\fields\SuperTableField->getSettingsHtml()
#12 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/fields/Matrix.php(265): craft\fields\Matrix->_getFieldOptionsForConfigurator()
#13 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Extension/Core.php(1619): craft\fields\Matrix->getSettingsHtml()
#14 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\fields\Matrix), 'getSettingsHtml', Array, 'method', false, false)
#15 /Users/jamie/Documents/repos/spacecentre/public_html/storage/runtime/compiled_templates/71/71735dc5a1b367bb4e36f72cd3d11b97b99b807ad924a2b73fb4ab420c7bd9ba.php(246): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\fields\Matrix), 'getSettingsHtml', Array, 'method')
#16 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_8012aa2be78b6572a289ae998472e35a16717d81ca0bfaf3b1fd3332e04d7fd8->block_content(Array, Array)
#17 /Users/jamie/Documents/repos/spacecentre/public_html/storage/runtime/compiled_templates/b9/b9858c62d64bdccff7802f2823fb0be21ca51460993e808f3e569085276b677d.php(639): Twig_Template->displayBlock('content', Array, Array)
#18 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_61b5e9747e4d96007843ea0a713040d7dd51211ad8e3edbefe0ccbd724716ab7->block_main(Array, Array)
#19 /Users/jamie/Documents/repos/spacecentre/public_html/storage/runtime/compiled_templates/b9/b9858c62d64bdccff7802f2823fb0be21ca51460993e808f3e569085276b677d.php(536): Twig_Template->displayBlock('main', Array, Array)
#20 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_61b5e9747e4d96007843ea0a713040d7dd51211ad8e3edbefe0ccbd724716ab7->block_body(Array, Array)
#21 /Users/jamie/Documents/repos/spacecentre/public_html/storage/runtime/compiled_templates/f3/f37f6e47708831f41f20060087dcb3c330d6ec72482a95c190399ba2fc402487.php(60): Twig_Template->displayBlock('body', Array, Array)
#22 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_eb04b5a3219c42b8f279b55ddd17c651a934ee7eca441014a8f7a0561f0af8e7->doDisplay(Array, Array)
#23 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#24 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#25 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#26 /Users/jamie/Documents/repos/spacecentre/public_html/storage/runtime/compiled_templates/c8/c8d85d8a68a61e1c1233808f03707bcee95c4ea03e9f2a46f0d1f752def520e5.php(40): craft\web\twig\Template->display(Array, Array)
#27 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_4d237eca83f119304551669c4ad8397d47b2910d95019302c617ff9541a82634->doDisplay(Array, Array)
#28 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#29 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#30 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#31 /Users/jamie/Documents/repos/spacecentre/public_html/storage/runtime/compiled_templates/b9/b9858c62d64bdccff7802f2823fb0be21ca51460993e808f3e569085276b677d.php(94): craft\web\twig\Template->display(Array, Array)
#32 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_61b5e9747e4d96007843ea0a713040d7dd51211ad8e3edbefe0ccbd724716ab7->doDisplay(Array, Array)
#33 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#34 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#35 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#36 /Users/jamie/Documents/repos/spacecentre/public_html/storage/runtime/compiled_templates/71/71735dc5a1b367bb4e36f72cd3d11b97b99b807ad924a2b73fb4ab420c7bd9ba.php(95): craft\web\twig\Template->display(Array, Array)
#37 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_8012aa2be78b6572a289ae998472e35a16717d81ca0bfaf3b1fd3332e04d7fd8->doDisplay(Array, Array)
#38 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#39 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#40 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#41 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#42 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#43 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('settings/fields...', Array)
#44 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('settings/fields...', Array)
#45 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/Controller.php(155): craft\web\View->renderPageTemplate('settings/fields...', Array)
#46 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/controllers/FieldsController.php(243): craft\web\Controller->renderTemplate('settings/fields...', Array)
#47 [internal function]: craft\controllers\FieldsController->actionEditField(187, Object(craft\fields\PlainText), '16')
#48 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#49 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#50 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('edit-field', Array)
#51 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-field', Array)
#52 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('fields/edit-fie...', Array)
#53 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('fields/edit-fie...', Array)
#54 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#55 /Users/jamie/Documents/repos/spacecentre/public_html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#56 /Users/jamie/Documents/repos/spacecentre/public_html/web/index.php(21): yii\base\Application->run()
#57 {main}`

**Comment by jamielaughton** [comment]
Just realised this issue is being addressed, should have looked at the previous issues first!
