### ISSUE TITLE
 "Save as new entry" throws an exception

### ISSUE THREAD

**Issue by bitsfabrikvienna** [engram-design/SuperTable#216]
### Description

If you want to duplicate an existing entry with a super table in a section with multiple sites an exception occurs: "Attempting to save an element in an unsupported site."

The error does not happen if the section is only enabled for 1 site or the super table "Manage blocks on a per-site basis" is checked.

### Steps to reproduce

1. Create a section which is enabled for more than 1 site
2. Add an entry type with a super table field and leave "Manage blocks on a per-site basis" unchecked
3. Add a new entry
4. Duplicate the new entry with "Save as new entry"

### Stack trace
```
2018-12-04 14:10:38 [-][6767][lsskjem3u3i3okmbf2i269j94d][error][yii\web\HttpException:500] yii\base\Exception: Attempting to save an element in an unsupported site. in /var/www/vendor/craftcms/cms/src/services/Elements.php:398
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/services/Elements.php(613): craft\services\Elements->saveElement(Object(verbb\supertable\elements\SuperTableBlockElement), false, false)
#1 /var/www/vendor/verbb/super-table/src/services/SuperTableService.php(683): craft\services\Elements->duplicateElement(Object(verbb\supertable\elements\SuperTableBlockElement), Array)
#2 /var/www/vendor/verbb/super-table/src/fields/SuperTableField.php(699): verbb\supertable\services\SuperTableService->saveField(Object(verbb\supertable\fields\SuperTableField), Object(craft\elements\Entry))
#3 /var/www/vendor/craftcms/cms/src/base/Element.php(1841): verbb\supertable\fields\SuperTableField->afterElementSave(Object(craft\elements\Entry), true)
#4 /var/www/vendor/craftcms/cms/src/elements/Entry.php(1080): craft\base\Element->afterSave(true)
#5 /var/www/vendor/craftcms/cms/src/services/Elements.php(498): craft\elements\Entry->afterSave(true)
#6 /var/www/vendor/craftcms/cms/src/services/Elements.php(588): craft\services\Elements->saveElement(Object(craft\elements\Entry), false, false)
#7 /var/www/vendor/craftcms/cms/src/controllers/EntriesController.php(499): craft\services\Elements->duplicateElement(Object(craft\elements\Entry))
#8 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#9 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('save-entry', Array)
#12 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#13 /var/www/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('entries/save-en...', Array)
#14 /var/www/vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction('entries/save-en...', Array)
#15 /var/www/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /var/www/web/index.php(21): yii\base\Application->run()
#18 {main}

Next yii\web\ServerErrorHttpException: An error occurred when duplicating the entry. in /var/www/vendor/craftcms/cms/src/controllers/EntriesController.php:521
Stack trace:
#0 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#1 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('save-entry', Array)
#4 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#5 /var/www/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('entries/save-en...', Array)
#6 /var/www/vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction('entries/save-en...', Array)
#7 /var/www/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/web/index.php(21): yii\base\Application->run()
#10 {main}
```

### Additional info

- Plugin version: 2.0.14
- Craft version: 3.0.33

**Comment by ghost** [comment]
Same thing happens for me. Just updated today.

**Comment by ghost** [comment]
Tried rolling back to 2.0.11, but that didn't fix the issue for me.

**Comment by davefischoff** [comment]
I'm running into this issue as well. Using version 2.0.14.

**Comment by ghost** [comment]
Was anyone able to resolve this?

**Comment by engram-design** [comment]
This should be fixed in [2.1.0](https://github.com/verbb/super-table/releases/tag/2.1.0), but let me know if you're still having issues.

**Comment by ghost** [comment]
@engram-design seems after the update, all the content from affected tables is lost. my site rellies heavily on supertable and now basically all content is gone lol

**Comment by ghost** [comment]
or at least all content from matrix fields inside supertables inside another matrix is dropped.
