### ISSUE TITLE
 Argument 1 passed to craft\db\Connection::tableExists() must be of the type string

### ISSUE THREAD

**Issue by bfjare** [engram-design/SuperTable#227]
Slightly different error when updating super table to 2.1.4.3 on craft 3.1.2.2

```
TypeError: Argument 1 passed to craft\db\Connection::tableExists() must be of the type string, null given, called in /var/www/vendor/verbb/super-table/src/migrations/m190120_000000_fix_supertablecontent_tables.php on line 36

Migration: verbb\supertable\migrations\m190120_000000_fix_supertablecontent_tables

Output:

Exception: Argument 1 passed to craft\db\Connection::tableExists() must be of the type string, null given, called in /var/www/vendor/verbb/super-table/src/migrations/m190120_000000_fix_supertablecontent_tables.php on line 36 (/var/www/vendor/craftcms/cms/src/db/Connection.php:310)
#0 /var/www/vendor/verbb/super-table/src/migrations/m190120_000000_fix_supertablecontent_tables.php(36): craft\db\Connection->tableExists(NULL)
#1 /var/www/vendor/craftcms/cms/src/db/Migration.php(56): verbb\supertable\migrations\m190120_000000_fix_supertablecontent_tables->safeUp()
#2 /var/www/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#3 /var/www/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(verbb\supertable\migrations\m190120_000000_fix_supertablecontent_tables))
#4 /var/www/vendor/craftcms/cms/src/services/Updates.php(223): craft\db\MigrationManager->up()
#5 /var/www/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(445): craft\services\Updates->runMigrations(Array)
#6 /var/www/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#7 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#8 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#11 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#12 /var/www/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module-
```>runAction('updater/migrate', Array)
#13 /var/www/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#14 /var/www/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#15 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /var/www/public/index.php(21): yii\base\Application->run()
#17 {main}

**Comment by engram-design** [comment]
This should be fixed in [2.1.5](https://github.com/verbb/super-table/releases/tag/2.1.5), sorry for the issue and let me know if there are any further issues.

If you run into any issues after migration, be sure to run the new `http://mysite.com/actions/super-table/plugin/check-content-tables` action endpoint to check Super Table content tables.
