### ISSUE TITLE
Duplicate multisite entries with supertables

### ISSUE THREAD

**Issue by pieterjandebruyne** [engram-design/SuperTable#231]
### Description

Hi, I have a craft 3 multisite setup with 2 languages. I use a supertable to input an image/label/lightswitch.
My problem occured when I want to duplicate an entry from the control panel or inside of an entry by choosing save as a new entry.

Scenario 1:
If I have "Manage blocks on a per-site basis" checked it will make a copy of the entry but leave my second language empty (other fields with the right locale data are copied, only the supertable is empty)

Scenario 2:
If I do not have "Manage blocks on a per-site basis" checked it gives me an error "Could not duplicate elements due to validation errors.".

- if I go into the entry with devmode enables I get redirected to a 500 error:

```
Next yii\web\ServerErrorHttpException: An error occurred when duplicating the entry. in /............./vendor/craftcms/cms/src/controllers/EntriesController.php:521
Stack trace:
#0 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#1 /......../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /......../vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /......../vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('save-entry', Array)
#4 /......../vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#5 /......../vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('entries/save-en...', Array)
#6 /......../vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction('entries/save-en...', Array)
#7 /......../vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /......../vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /......../public_html/index.php(21): yii\base\Application->run()
#10 /........./.composer/vendor/laravel/valet/server.php(151): require('/Users/pieterja...')
#11 {main}
Copy Stacktrace Search Stackoverflow Search Google Exception
HTTP 500 – Internal Server Error – yii\web\ServerErrorHttpException
An error occurred when duplicating the entry.
↵
Caused by: Exception – yii\base\Exception
Element 468 doesn’t exist in the site 2
in /......../vendor/craftcms/cms/src/services/Elements.php at line 601
```

--> What I really need is to duplicate an array using the second scenario without "Manage blocks on a per-site basis" checked and only the label field translateable (translation method == translate for each language)

Note: Not sure if this is resolvable by super table or craft itself..

### Steps to reproduce

1. Setup a multisite with an entry that exists on 2 languages and has a supertable field.
2. duplicate that field.

### Additional info

- Plugin version: Super table = dev-craft-3
- Craft version: 3.0.36

**Comment by engram-design** [comment]
Can you confirm what version of Super Table you're on? `dev-craft-3` will almost certainly not work on a 3.0.x install due to it requiring 3.1.x.

I do believe this may have been fixed in [2.1.0](https://github.com/verbb/super-table/releases/tag/2.1.0)

**Comment by engram-design** [comment]
Closing due to inactivity, but do ping me if this needs to be reopened.

**Comment by pieterjandebruyne** [comment]
Sorry for the late response, 
It was dev-craft-3 and a 3.0.36 install as I mentioned before..
I had some problems with craft 3.1 on another install and don't want to upgrade yet.. But duplicating should be working fine once I upgrade ?

Thx

**Comment by TomDeSmet** [comment]
Hi, I'm having the same issue today, just updated tot he latest Craft and installed Super Table and I get the issue. Doesn't help for me to enable the "Manage blocks on a per-site basis" setting.
I also get an internal server error when trying to re-save all blocks from the settings page.
