### ISSUE TITLE
Migration issues 2 to 3.1

### ISSUE THREAD

**Issue by bossanova808** [engram-design/SuperTable#238]
### Description

Ok Josh, so just putting this somewhere other than Slack so you've got a reference.

During the main migration:

```
    > Trying to create missing content table for #21 ...
    > Field mismatch craft\fields\MissingField is not a Super Table field ...
    > Trying to create missing content table for #66 ...
    > Field mismatch craft\fields\MissingField is not a Super Table field ...
    > Trying to create missing content table for #126 ...
    > Field mismatch craft\fields\MissingField is not a Super Table field ...
    > Trying to create missing content table for #211 ...
    > Field mismatch craft\fields\MissingField is not a Super Table field ...
    > Trying to create missing content table for #312 ...
    > Field mismatch craft\fields\MissingField is not a Super Table field ...
    > Trying to create missing content table for #372 ...
    > Field mismatch craft\fields\MissingField is not a Super Table field ...
    > Trying to create missing content table for #48 ...
    > Field mismatch craft\fields\MissingField is not a Super Table field ...
    > Trying to create missing content table for #52 ...
    > Field mismatch craft\fields\MissingField is not a Super Table field ...
    > Trying to create missing content table for #86 ...
    > Field mismatch craft\fields\MissingField is not a Super Table field ...
```

..but the up migration  completes without any other errors.

I then visit:
https://c3-dev.imagescience.net.au/actions/super-table/plugin/check-content-tables

```
> ERROR: Super Table field #21 is missing its content table in settings ...
> ERROR: Super Table field #66 is missing its content table in settings ...
> ERROR: Super Table field #126 is missing its content table in settings ...
> ERROR: Super Table field #211 is missing its content table in settings ...
> ERROR: Super Table field #312 is missing its content table in settings ...
> ERROR: Super Table field #372 is missing its content table in settings ...
> ERROR: Super Table field #48 is missing its content table in settings ...
> ERROR: Super Table field #52 is missing its content table in settings ...
> ERROR: Super Table field #86 is missing its content table in settings ...

Fix the above errors by running the Super Table content table fixer.
```

Click on the link and then:

```
 Trying to create missing content table for #21 ...
> Generated table name {{%stc_productspecs}} ...
> update in {{%fields}} ... done (time: 0.004s)
> Local field table name {{%stc_productspecs}} ...
> Updated Super Table field after content table creation ...

> Trying to create missing content table for #66 ...
> Generated table name {{%stc_videoconnections}} ...
> update in {{%fields}} ... done (time: 0.005s)
> Local field table name {{%stc_videoconnections}} ...
> Updated Super Table field after content table creation ...

> Trying to create missing content table for #126 ...
> Generated table name {{%stc_gamut}} ...
> update in {{%fields}} ... done (time: 0.006s)
> Local field table name {{%stc_gamut}} ...
> Updated Super Table field after content table creation ...

> Trying to create missing content table for #211 ...
> Generated table name {{%stc_upsell}} ...
> update in {{%fields}} ... done (time: 0.007s)
> Local field table name {{%stc_upsell}} ...
> Updated Super Table field after content table creation ...

> Trying to create missing content table for #312 ...
> Generated table name {{%stc_inprogressevents}} ...
> update in {{%fields}} ... done (time: 0.008s)
> Local field table name {{%stc_inprogressevents}} ...
Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0' at line 1
The SQL being executed was: ALTER TABLE `craft_stc_inprogressevents` CHANGE `field_ticketed` `field_ticketed` 0 (/var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `cr...')
#1 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE `cr...')
#2 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/services/Fields.php(1438): yii\db\Command->execute()
#3 /var/www/vhosts/c3-dev/vendor/verbb/super-table/src/services/SuperTableService.php(361): craft\services\Fields->applyFieldSave('7c34f2c4-099b-4...', Array, 'superTableBlock...')
#4 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(821): verbb\supertable\services\SuperTableService->handleChangedBlockType(Object(craft\events\ConfigEvent))
#5 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#6 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#7 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(510): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#8 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/services/ProjectConfig.php(364): craft\services\ProjectConfig->processConfigChanges('superTableBlock...', true)
#9 /var/www/vhosts/c3-dev/vendor/verbb/super-table/src/services/SuperTableService.php(295): craft\services\ProjectConfig->set('superTableBlock...', Array)
#10 /var/www/vhosts/c3-dev/vendor/verbb/super-table/src/services/SuperTableService.php(615): verbb\supertable\services\SuperTableService->saveBlockType(Object(verbb\supertable\models\SuperTableBlockTypeModel), false)
#11 /var/www/vhosts/c3-dev/vendor/verbb/super-table/src/migrations/m190120_000000_fix_supertablecontent_tables.php(199): verbb\supertable\services\SuperTableService->saveSettings(Object(verbb\supertable\fields\SuperTableField))
#12 /var/www/vhosts/c3-dev/vendor/verbb/super-table/src/migrations/m190120_000000_fix_supertablecontent_tables.php(49): verbb\supertable\migrations\m190120_000000_fix_supertablecontent_tables->_createContentTable(Array, Array)
#13 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/db/Migration.php(56): verbb\supertable\migrations\m190120_000000_fix_supertablecontent_tables->safeUp()
#14 /var/www/vhosts/c3-dev/vendor/verbb/super-table/src/controllers/PluginController.php(32): craft\db\Migration->up()
#15 [internal function]: verbb\supertable\controllers\PluginController->actionFixContentTables()
#16 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#18 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('fix-content-tab...', Array)
#19 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('fix-content-tab...', Array)
#20 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('super-table/plu...', Array)
#21 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('super-table/plu...', Array)
#22 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#23 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#24 /var/www/vhosts/c3-dev/web/index.php(21): yii\base\Application->run()
#25 {main}

Fixes complete.
```

(That's an incognito field BTW)

### Steps to reproduce

See ^ 

### Additional info

Ran composer update before this, and pulled fresh db from live site...so all the latest gear...

- Plugin version: Latest
- Craft version: Latest

**Comment by bossanova808** [comment]
IF I then re-run the fixes I then get:

```
> Super Table field #21 has content table {{%stc_productspecs}} ...
> Super Table field #66 has content table {{%stc_videoconnections}} ...
> Super Table field #126 has content table {{%stc_gamut}} ...
> Super Table field #211 has content table {{%stc_upsell}} ...
> Super Table field #312 has content table {{%stc_inprogressevents}} ...
> Trying to create missing content table for #372 ...
> Generated table name {{%stc_superreceiptbanner}} ...
> update in {{%fields}} ... done (time: 0.004s)
> Local field table name {{%stc_superreceiptbanner}} ...
> Updated Super Table field after content table creation ...

> Trying to create missing content table for #48 ...
> Generated table name {{%stc_9_featurelist}} ...
> update in {{%fields}} ... done (time: 0.010s)
> Local field table name {{%stc_9_featurelist}} ...
> Updated Super Table field after content table creation ...

> Trying to create missing content table for #52 ...
> Generated table name {{%stc_10_accordion}} ...
> update in {{%fields}} ... done (time: 0.008s)
> Local field table name {{%stc_10_accordion}} ...
> Updated Super Table field after content table creation ...

> Trying to create missing content table for #86 ...
> Generated table name {{%stc_13_imagestable}} ...
> update in {{%fields}} ... done (time: 0.006s)
> Local field table name {{%stc_13_imagestable}} ...
> Updated Super Table field after content table creation ...


Fixes complete.
```

**Comment by engram-design** [comment]
I'm still not sure why Craft doesn't handle the component (field) registration of Super Table during this upgrade. That's the reason for the first issue, but re-running the migration should kick things into gear.

The second error around `field_ticketed` is something I haven't seen before...

**Comment by bossanova808** [comment]
So that is an incognito filed (that I fill programmatically  during split order processing system in the back end inside a Commerce order).  But given it is changing the table here I guess data is not involved?  As it's possible there are some rows from early testing with bogus data still, I guess.

Perhaps we can get into this once I'm ready for you...almost there I think.   Most things are working again finally, so probably about mid week I'll send you some stuff.  Late Friday arvo I was finally able to dig into some new work (fixing up the totally changed SEOMatic stuff is first cab on that rank...)

(PS 11:30 on a Saturday night?!)

**Comment by engram-design** [comment]
Might just close this one, as I think you managed to make these errors go away with the latest version @bossanova808 ?

**Comment by bossanova808** [comment]
Well, I do still have to run the correction thing manually, and I am not sure that the actual data is migrating fully correctly - I have just hit an error:

```
Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_description' in 'field list'
The SQL being executed was: SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `supertableblocks`.`fieldId`, `supertableblocks`.`ownerId`, `supertableblocks`.`ownerSiteId`, `supertableblocks`.`typeId`, `supertableblocks`.`sortOrder`, `content`.`id` AS `contentId`, `content`.`field_header`, `content`.`field_description`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `craft_elements` `elements`
INNER JOIN `craft_supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `elements`.`id`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `craft_stc_9_featurelist` `content` ON `content`.`elementId` = `elements`.`id`
WHERE (`supertableblocks`.`fieldId`='48') AND (`supertableblocks`.`ownerId`='394') AND (`elements_sites`.`siteId`=1) AND (`content`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND (`elements`.`enabled`=TRUE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`enabled`=TRUE)
ORDER BY `supertableblocks`.`sortOrder`) `subquery`
INNER JOIN `craft_supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `craft_stc_9_featurelist` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `supertableblocks`.`sortOrder`

Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'content.field_description' in 'field list'
)

↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_description' in 'field list'

in /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Command.php at line 1258
```

..but we can look at this more once we start the work together bit if you like.

**Comment by florentineprinzessinzusachsen** [comment]
I seem to be hitting a similar problem, running the latest version of craft cms (3.1.12) and super table (2.1.8). When loading any entry I get the following type of errors:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_buttonIcon' in 'field list'
The SQL being executed was: SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `supertableblocks`.`fieldId`, `supertableblocks`.`ownerId`, `supertableblocks`.`ownerSiteId`, `supertableblocks`.`typeId`, `supertableblocks`.`sortOrder`, `content`.`id` AS `contentId`, `content`.`field_headline`, `content`.`field_subheadline`, `content`.`field_colorHeadlineSubheadline`, `content`.`field_buttonIcon`, `content`.`field_position`, `content`.`field_showPostDate`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `craft_elements` `elements`
INNER JOIN `craft_supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `elements`.`id`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `craft_stc_58_headlinesubheadlinebutton` `content` ON `content`.`elementId` = `elements`.`id`
WHERE (`supertableblocks`.`fieldId`='545') AND (`supertableblocks`.`ownerId`='17819') AND (`elements_sites`.`siteId`=1) AND (`content`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL)
ORDER BY `supertableblocks`.`sortOrder`) `subquery`
INNER JOIN `craft_supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `craft_stc_58_headlinesubheadlinebutton` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `supertableblocks`.`sortOrder`
Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'content.field_buttonIcon' in 'field list'
)
↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_buttonIcon' in 'field list'
in /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/db/Command.php at line 1258
```

The table fixer does not report and thus does not fix any errors. I looked into the migration output and found the following error.

```
    > Trying to create missing content table for #1905 ...
    > Generated table name {{%stc_171_columns}} ...
    > update in {{%fields}} ... done (time: 0.149s)
    > Local field table name {{%stc_171_columns}} ...
Exception: Invalid validation rule: a rule must specify both attribute names and validator type. (/Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/Model.php:461)
#0 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/Model.php(420): yii\base\Model->createValidators()
#1 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/Model.php(189): yii\base\Model->getValidators()
#2 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/Model.php(354): yii\base\Model->scenarios()
#3 /Users/wojteckir2/www/haebmau.space/vendor/verbb/super-table/src/services/SuperTableService.php(173): yii\base\Model->validate()
#4 /Users/wojteckir2/www/haebmau.space/vendor/verbb/super-table/src/services/SuperTableService.php(531): verbb\supertable\services\SuperTableService->validateBlockType(Object(verbb\supertable\models\SuperTableBlockTypeModel), false)
#5 /Users/wojteckir2/www/haebmau.space/vendor/verbb/super-table/src/services/SuperTableService.php(579): verbb\supertable\services\SuperTableService->validateFieldSettings(Object(verbb\supertable\fields\SuperTableField))
#6 /Users/wojteckir2/www/haebmau.space/vendor/verbb/super-table/src/migrations/m190120_000000_fix_supertablecontent_tables.php(221): verbb\supertable\services\SuperTableService->saveSettings(Object(verbb\supertable\fields\SuperTableField))
#7 /Users/wojteckir2/www/haebmau.space/vendor/verbb/super-table/src/migrations/m190120_000000_fix_supertablecontent_tables.php(138): verbb\supertable\migrations\m190120_000000_fix_supertablecontent_tables->_createContentTable(Array, Array)
#8 /Users/wojteckir2/www/haebmau.space/vendor/craftcms/cms/src/db/Migration.php(56): verbb\supertable\migrations\m190120_000000_fix_supertablecontent_tables->safeUp()
#9 /Users/wojteckir2/www/haebmau.space/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#10 /Users/wojteckir2/www/haebmau.space/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(verbb\supertable\migrations\m190120_000000_fix_supertablecontent_tables))
#11 /Users/wojteckir2/www/haebmau.space/vendor/craftcms/cms/src/services/Updates.php(223): craft\db\MigrationManager->up()
#12 /Users/wojteckir2/www/haebmau.space/vendor/craftcms/cms/src/console/controllers/MigrateController.php(252): craft\services\Updates->runMigrations(Array)
#13 [internal function]: craft\console\controllers\MigrateController->actionAll()
#14 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#17 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#18 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#19 /Users/wojteckir2/www/haebmau.space/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#20 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#21 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#22 /Users/wojteckir2/www/haebmau.space/craft(22): yii\base\Application->run()
#23 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Super Table.'

in /Users/wojteckir2/www/haebmau.space/vendor/craftcms/cms/src/services/Updates.php:231

Stack trace:
#0 /Users/wojteckir2/www/haebmau.space/vendor/craftcms/cms/src/console/controllers/MigrateController.php(252): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#5 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /Users/wojteckir2/www/haebmau.space/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#8 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /Users/wojteckir2/www/haebmau.space/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /Users/wojteckir2/www/haebmau.space/craft(22): yii\base\Application->run()
#11 {main}
```
Please let me know if you need any additional information or how I can be of further help in fixing this.

And many thanks for your ongoing support!

**Comment by roelvanhintum** [comment]
Looks like the table fixer is only checking for missing content tables. It doesn't check for missing columns in the content tables. It completely blocks all saving operations for those supertable fields and fields groups containing the supertable field.

**Comment by engram-design** [comment]
There have been a number of improvements to project config for both Super Table and Matrix in [2.1.9](https://github.com/verbb/super-table/releases/tag/2.1.9).

I've also added a new settings page for the checker/fixer, along with making sure to check for the correct columns in Super Table content tables.
