### ISSUE TITLE
Installing SuperTable with Project Config fails

### ISSUE THREAD

**Issue by boboldehampsink** [engram-design/SuperTable#247]
### Description

```bash
web_1         |     > applying existing project config ... Exception: Argument 1 passed to craft\db\Connection::columnExists() must be of the type string, null given, called in /app/user/vendor/craftcms/cms/src/services/Fields.php on line 1436 (/app/user/vendor/craftcms/cms/src/db/Connection.php:366)
web_1         | #0 /app/user/vendor/craftcms/cms/src/services/Fields.php(1436): craft\db\Connection->columnExists(NULL, 'field_')
web_1         | #1 /app/user/vendor/verbb/super-table/src/services/SuperTableService.php(367): craft\services\Fields->applyFieldSave('9996e4e1-eadd-4...', Array, 'superTableBlock...')
web_1         | #2 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(905): verbb\supertable\services\SuperTableService->handleChangedBlockType(Object(craft\events\ConfigEvent))
web_1         | #3 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(419): craft\services\ProjectConfig->_applyChanges(Array)
web_1         | #4 /app/user/vendor/craftcms/cms/src/migrations/Install.php(1036): craft\services\ProjectConfig->applyYamlChanges()
web_1         | #5 /app/user/vendor/craftcms/cms/src/migrations/Install.php(71): craft\migrations\Install->insertDefaultData()
web_1         | #6 /app/user/vendor/craftcms/cms/src/db/Migration.php(56): craft\migrations\Install->safeUp()
web_1         | #7 /app/user/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
web_1         | #8 /app/user/vendor/craftcms/cms/src/console/controllers/InstallController.php(161): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
web_1         | #9 [internal function]: craft\console\controllers\InstallController->actionCraft()
web_1         | #10 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
web_1         | #11 /app/user/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
web_1         | #12 /app/user/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
web_1         | #13 /app/user/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
web_1         | #14 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
web_1         | #15 /app/user/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('install', Array)
web_1         | #16 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
web_1         | #17 /app/user/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
web_1         | #18 /app/user/craft(23): yii\base\Application->run()
web_1         | #19 {main}
web_1         | Exception 'craft\errors\MigrationException' with message 'An error occurred while executing the "craft\migrations\Install migration: Argument 1 passed to craft\db\Connection::columnExists() must be of the type string, null given, called in /app/user/vendor/craftcms/cms/src/services/Fields.php on line 1436'
web_1         | 
web_1         | in /app/user/vendor/craftcms/cms/src/db/MigrationManager.php:260
web_1         | 
web_1         | Stack trace:
web_1         | #0 /app/user/vendor/craftcms/cms/src/console/controllers/InstallController.php(161): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
web_1         | #1 [internal function]: craft\console\controllers\InstallController->actionCraft()
web_1         | #2 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
web_1         | #3 /app/user/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
web_1         | #4 /app/user/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
web_1         | #5 /app/user/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
web_1         | #6 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
web_1         | #7 /app/user/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('install', Array)
web_1         | #8 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
web_1         | #9 /app/user/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
web_1         | #10 /app/user/craft(23): yii\base\Application->run()
web_1         | #11 {main}
```

### Steps to reproduce

1. Install Craft with Supertable from an existing project.yaml

### Additional info

- Plugin version: 2.1.9
- Craft version: 3.1.13

**Comment by engram-design** [comment]
Should be fixed in [2.1.10](https://github.com/verbb/super-table/releases/tag/2.1.10). This is built into the migration from < Craft 3.1.x, so future upgrades shouldn't have this issue.

However, you'll need to either run the checker/fixer tool (in Super Table settings) to fix your current project config, or manually edit the `contentTable` values for each Super Table field in your project.yaml file.
