### ISSUE TITLE
Undefined index: type m190227_100000_fix_project_config.php

### ISSUE THREAD

**Issue by davist11** [engram-design/SuperTable#275]
### Description
We are getting an error upgrading Super Table from 2.0.14 to 2.1.20

```
Yii Migration Tool (based on Yii v2.0.19)

Exception: Undefined index: type (/Users/tdavis/sites/hamilton/vendor/verbb/super-table/src/migrations/m190227_100000_fix_project_config.php:104)
#0 /Users/tdavis/sites/hamilton/vendor/verbb/super-table/src/migrations/m190227_100000_fix_project_config.php(104): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/tdavis/s...', 104, Array)
#1 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/Migration.php(56): verbb\supertable\migrations\m190227_100000_fix_project_config->safeUp()
#2 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#3 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(verbb\supertable\migrations\m190227_100000_fix_project_config))
#4 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#5 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/console/controllers/MigrateController.php(252): craft\services\Updates->runMigrations(Array)
#6 [internal function]: craft\console\controllers\MigrateController->actionAll()
#7 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#10 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#11 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#12 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#13 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#14 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /Users/tdavis/sites/hamilton/craft(22): yii\base\Application->run()
#16 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Super Table.'

in /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Updates.php:233

Stack trace:
#0 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/console/controllers/MigrateController.php(252): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#5 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#8 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /Users/tdavis/sites/hamilton/craft(22): yii\base\Application->run()
#11 {main}
```

### Additional info

- Plugin version: 2.1.20
- Craft version: 3.1.28

**Comment by engram-design** [comment]
Seems like you project config is missing the `type` property, describing what field it is, which I've not need before. This should be fixed in https://github.com/verbb/super-table/commit/bd8d61790229cedcfe7f50081aa4efe27e84a4ba and will be in the next release.

**Comment by davist11** [comment]
Ok great. Any sense when the next release will be?

**Comment by davist11** [comment]
@engram-design just wanted to bump this to see when you'd be pushing out a new release with this fix? Thanks!

**Comment by engram-design** [comment]
Sorry for the delay, part of [2.1.21](https://github.com/verbb/super-table/releases/tag/2.1.21)
