### ISSUE TITLE
Error on project-config/sync

### ISSUE THREAD

**Issue by timkelty** [engram-design/SuperTable#312]
After upgrading a site from Craft 2, I made project.yaml changes and then ran `craft project-config/sync`.

Got this error: 

```
error: Argument 1 passed to craft\db\Connection::columnExists() must be of the type string, null given, called in /app/vendor/composer/craftcms/cms/src/services/Fields.php on line 940
[2019-11-05 14:17:27] craftcms.ERROR: TypeError: Argument 1 passed to craft\db\Connection::columnExists() must be of the type string, null given, called in /app/vendor/composer/craftcms/cms/src/services/Fields.php on line 940 and defined in /app/vendor/composer/craftcms/cms/src/db/Connection.php:400
Stack trace:
#0 /app/vendor/composer/craftcms/cms/src/services/Fields.php(940): craft\db\Connection->columnExists(NULL, 'field_length')
#1 /app/vendor/composer/craftcms/cms/src/services/Fields.php(880): craft\services\Fields->applyFieldDelete('d0c4b5a9-65fe-4...')
#2 /app/vendor/composer/verbb/super-table/src/services/SuperTableService.php(496): craft\services\Fields->deleteField(Object(craft\fields\MissingField))
#3 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(867): verbb\supertable\services\SuperTableService->handleDeletedBlockType(Object(craft\events\ConfigEvent))
#4 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#5 /app/vendor/composer/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#6 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(541): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#7 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(861): craft\services\ProjectConfig->processConfigChanges('superTableBlock...')
#8 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#9 /app/vendor/composer/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#10 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(541): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#11 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(935): craft\services\ProjectConfig->processConfigChanges('superTableBlock...')
#12 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(436): craft\services\ProjectConfig->_applyChanges(Array)
#13 /app/vendor/composer/craftcms/cms/src/console/controllers/ProjectConfigController.php(87): craft\services\ProjectConfig->applyYamlChanges()
#14 [internal function]: craft\console\controllers\ProjectConfigController->actionSync()
#15 /app/vendor/composer/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /app/vendor/composer/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /app/vendor/composer/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('sync', Array)
#18 /app/vendor/composer/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('sync', Array)
#19 /app/vendor/composer/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('sync', Array)
#20 /app/vendor/composer/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#21 /app/vendor/composer/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('project-config/...', Array)
#22 /app/vendor/composer/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#23 /app/vendor/composer/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#24 /app/bin/craft(7): yii\base\Application->run()
#25 {main} {"trace":[],"memory":46569328,"category":"TypeError","exception":"[object] (TypeError(code: 0): Argument 1 passed to craft\\db\\Connection::columnExists() must be of the type string, null given, called in /app/vendor/composer/craftcms/cms/src/services/Fields.php on line 940 at /app/vendor/composer/craftcms/cms/src/db/Connection.php:400)"} []``

**Comment by engram-design** [comment]
It looks like there are some issues with the Super Table containing a missing field. This can pretty easily happen from Craft 2 > 3. Can you confirm if you ran the content table checker/fixers?
