### ISSUE TITLE
[3.5.0-RC1] Cannot delete field: "Invalid owner ID"

### ISSUE THREAD

**Issue by timkelty** [engram-design/SuperTable#369]
Trying to delete a field in 3.5.0-RC1

```
2020-07-21 14:31:41 [-][2][42956474ed1f98b1cebb40ded776222a][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 83466 in /app/vendor/composer/verbb/super-table/src/elements/SuperTableBlockElement.php:291
Stack trace:
#0 /app/vendor/composer/craftcms/cms/src/helpers/ElementHelper.php(385): verbb\supertable\elements\SuperTableBlockElement->getOwner()
#1 /app/vendor/composer/craftcms/cms/src/helpers/ElementHelper.php(399): craft\helpers\ElementHelper::rootElement(Object(verbb\supertable\elements\SuperTableBlockElement))
#2 /app/vendor/composer/craftcms/cms/src/services/Elements.php(1411): craft\helpers\ElementHelper::isDraftOrRevision(Object(verbb\supertable\elements\SuperTableBlockElement))
#3 /app/vendor/composer/verbb/super-table/src/services/SuperTableService.php(489): craft\services\Elements->deleteElement(Object(verbb\supertable\elements\SuperTableBlockElement))
#4 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(1087): verbb\supertable\services\SuperTableService->handleDeletedBlockType(Object(craft\events\ConfigEvent))
#5 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#6 /app/vendor/composer/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#7 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(659): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#8 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(476): craft\services\ProjectConfig->processConfigChanges('superTableBlock...', true, 'Delete super ta...')
#9 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(492): craft\services\ProjectConfig->set('superTableBlock...', NULL, 'Delete super ta...')
#10 /app/vendor/composer/verbb/super-table/src/services/SuperTableService.php(447): craft\services\ProjectConfig->remove('superTableBlock...', 'Delete super ta...')
#11 /app/vendor/composer/verbb/super-table/src/services/SuperTableService.php(699): verbb\supertable\services\SuperTableService->deleteBlockType(Object(verbb\supertable\models\SuperTableBlockTypeModel))
#12 /app/vendor/composer/verbb/super-table/src/fields/SuperTableField.php(907): verbb\supertable\services\SuperTableService->deleteSuperTableField(Object(verbb\supertable\fields\SuperTableField))
#13 /app/vendor/composer/craftcms/cms/src/services/Fields.php(926): verbb\supertable\fields\SuperTableField->beforeApplyDelete()
#14 /app/vendor/composer/craftcms/cms/src/services/Fields.php(892): craft\services\Fields->applyFieldDelete('a60d8d0a-f361-4...')
#15 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(1087): craft\services\Fields->handleDeletedField(Object(craft\events\ConfigEvent))
#16 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#17 /app/vendor/composer/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#18 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(659): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#19 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(476): craft\services\ProjectConfig->processConfigChanges('fields.a60d8d0a...', true, 'Delete the \xE2\x80\x9Co...')
#20 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(492): craft\services\ProjectConfig->set('fields.a60d8d0a...', NULL, 'Delete the \xE2\x80\x9Co...')
#21 /app/vendor/composer/craftcms/cms/src/services/Fields.php(871): craft\services\ProjectConfig->remove('fields.a60d8d0a...', 'Delete the \xE2\x80\x9Co...')
#22 /app/vendor/composer/craftcms/cms/src/services/Fields.php(847): craft\services\Fields->deleteField(Object(verbb\supertable\fields\SuperTableField))
#23 /app/vendor/composer/craftcms/cms/src/controllers/FieldsController.php(335): craft\services\Fields->deleteFieldById(41)
#24 [internal function]: craft\controllers\FieldsController->actionDeleteField()
#25 /app/vendor/composer/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#26 /app/vendor/composer/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#27 /app/vendor/composer/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('delete-field', Array)
#28 /app/vendor/composer/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('delete-field', Array)
#29 /app/vendor/composer/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction('fields/delete-f...', Array)
#30 /app/vendor/composer/craftcms/cms/src/web/Application.php(597): craft\web\Application->runAction('fields/delete-f...', Array)
#31 /app/vendor/composer/craftcms/cms/src/web/Application.php(274): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#32 /app/vendor/composer/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#33 /app/public/index.php(5): yii\base\Application->run()
#34 {main}
```

**Comment by engram-design** [comment]
Can you provide some further details as I can't replicate.

- Is this a Matrix Super Table combination field?
- Is this an upgraded Craft site from 3.4, or a fresh install?
- Does this happen for all Super Table fields?
- Is this a multi-site?

**Comment by timkelty** [comment]
> Is this a Matrix Super Table combination field?

Nope!
> Is this an upgraded Craft site from 3.4, or a fresh install?

Upgraded from 3.4!

> Does this happen for all Super Table fields?

Yep! (but I only have a couple)

> Is this a multi-site?

Nope!

**Comment by timkelty** [comment]
The fields and ST block types get removed from my project config files when I do this.

However, if I then try to run `craft project-config/apply`, I get the same error on the command line.

**Comment by engram-design** [comment]
Thanks for the info - will aim to do some more testing...

**Comment by darylknight** [comment]
I'm guessing this is related to https://github.com/craftcms/cms/issues/6780.

The site this is happening on is based on my boilerplate site, which is 2 years old.

**Comment by engram-design** [comment]
Looks like this is fixed in https://github.com/craftcms/cms/issues/6780 - let me know if not
