### ISSUE TITLE
Project config sync errors in read-only mode

### ISSUE THREAD

**Issue by roelvanhintum** [engram-design/SuperTable#375]
There are problems with the config sync while in read-only mode, as described in https://github.com/craftcms/cms/issues/3957. I did some digging and found that it happens (for me) inside super-table and linkit fields. It looks like super-table is the only one doing something with project-config.
I’ve added the stack trace and the stuff I found in craft’s ProjectConfig.php (var_dumps are current and new)

**Steps to reproduce**
1. Make sure craft has `allowAdminChanges` set to false on server
2. Create a supertable field
3. Deploy created project.yml to server
4. Execute project-config/sync on server

**Additional info**
- Plugin version: 2.5.4
- Craft version: 3.4.30
- Multi-site: Yes

**Additional context**
[new.log](https://github.com/verbb/super-table/files/5040479/new.log)
[current.log](https://github.com/verbb/super-table/files/5040480/current.log)

Stacktrace:
```log
2020-07-31 16:07:44 [-][-][-][error][yii\base\NotSupportedException] yii\base\NotSupportedException: Changes to the project config are not possible while in read-only mode. in /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php:441
Stack trace:
#0 /var/www/vendor/verbb/super-table/src/services/SuperTableService.php(319): craft\services\ProjectConfig->set()
#1 /var/www/vendor/verbb/super-table/src/services/SuperTableService.php(655): verbb\supertable\services\SuperTableService->saveBlockType()
#2 /var/www/vendor/verbb/super-table/src/fields/SuperTableField.php(935): verbb\supertable\services\SuperTableService->saveSettings()
#3 /var/www/vendor/craftcms/cms/src/services/Fields.php(1567): verbb\supertable\fields\SuperTableField->afterSave()
#4 /var/www/vendor/craftcms/cms/src/services/Matrix.php(375): craft\services\Fields->applyFieldSave()
#5 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(1103): craft\services\Matrix->handleChangedBlockType()
#6 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#7 /var/www/vendor/yiisoft/yii2/base/Component.php(627): call_user_func()
#8 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(679): yii\base\Component->trigger()
#9 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(1093): craft\services\ProjectConfig->processConfigChanges()
#10 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#11 /var/www/vendor/yiisoft/yii2/base/Component.php(627): call_user_func()
#12 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(679): yii\base\Component->trigger()
#13 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(1198): craft\services\ProjectConfig->processConfigChanges()
#14 /var/www/vendor/craftcms/cms/src/services/ProjectConfig.php(540): craft\services\ProjectConfig->_applyChanges()
#15 /var/www/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(87): craft\services\ProjectConfig->applyYamlChanges()
#16 [internal function]: craft\console\controllers\ProjectConfigController->actionSync()
#17 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#18 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#19 /var/www/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction()
#20 /var/www/vendor/craftcms/cms/src/console/Controller.php(187): yii\console\Controller->runAction()
#21 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction()
#22 /var/www/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#23 /var/www/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction()
#24 /var/www/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#25 /var/www/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#26 /var/www/craft(23): yii\base\Application->run()
#27 {main}
```

**Comment by engram-design** [comment]
Can you try [2.6.0](https://github.com/verbb/super-table/releases/tag/2.6.0) to see if this issue persists?

**Comment by roelvanhintum** [comment]
@engram-design thanks! That seems to solve it.
