### ISSUE TITLE
Calling unknown method: craft\fieldlayoutelements\CustomField::hasErrors()

### ISSUE THREAD

**Issue by nesh-ram** [engram-design/SuperTable#390]
After updating craft from 3.4.22.1 to 3.5.14 and plugin from 2.4.9 to 2.6.3 getting error when opening the super table field in settings page
![2020-11-10](https://user-images.githubusercontent.com/1815036/98774566-42e0ba00-2411-11eb-8668-7d8d57b00836.png)

**Comment by nesh-ram** [comment]
Got Calling unknown method: craft\fields\Entries::getField() before updating plugin version to 2.6.3 and only updating cms

**Comment by engram-design** [comment]
The screenshot is too small to make out I'm afraid, but it seems to refer to a `CustomField::hasErrors()` which isn't anything to do with Super Table.

With regards to the `craft\fields\Entries::getField()` error when did you receive this error? Did you get this error after updating Craft from 3.4.22.1 to 3.5.14, but before updating Super Table? Ideally, you should be doing both at the same time. It'd probably need a bit more information (a stack trace) of that issue.

**Comment by mcclaskiem** [comment]
I am getting this issue as well.

```
craftcms/cms": "3.5.17.1"
verbb/super-table": "2.6.5",
```

```
Stack Trace:
Twig\Error\RuntimeError: Calling unknown method: craft\fieldlayoutelements\CustomField::hasErrors() in /home/forge/gencon-admin-staging.thesmithy.io/vendor/verbb/super-table/src/templates/settings.html:15
Stack trace:
#0 /home/forge/gencon-admin-staging.thesmithy.io/storage/runtime/compiled_templates/8e/8e6afceee2eacf77e38fa49f379ba354938baf89fb8ad2490619415211ec64d7.php(85): craft\helpers\Template::attribute()
#1 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(407): __TwigTemplate_cf7b7b46bda59323a6db04ac17f3f61a632655fae843c170223caed4b4b424be->doDisplay()
#2 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#3 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(392): Twig\Template->display()
#4 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#5 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#6 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render()
#7 /home/forge/gencon-admin-staging.thesmithy.io/vendor/verbb/super-table/src/fields/SuperTableField.php(519): craft\web\View->renderTemplate()
#8 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Extension/CoreExtension.php(1499): verbb\supertable\fields\SuperTableField->getSettingsHtml()
#9 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute()
#10 /home/forge/gencon-admin-staging.thesmithy.io/storage/runtime/compiled_templates/d7/d7f66efd88c962d1d0ca93db4f660c94a029d8adb01bc136c2fdae3ce462121a.php(499): craft\helpers\Template::attribute()
#11 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(407): __TwigTemplate_5d9761765dae3fdc890a20ea0e0f4d5cb5859ac741e2773216f9f006200ff34f->doDisplay()
#12 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#13 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(392): Twig\Template->display()
#14 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#15 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#16 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render()
#17 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/fields/Matrix.php(480): craft\web\View->renderTemplate()
#18 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Extension/CoreExtension.php(1499): craft\fields\Matrix->getSettingsHtml()
#19 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute()
#20 /home/forge/gencon-admin-staging.thesmithy.io/storage/runtime/compiled_templates/39/397acfe4830a947c60ab99b668f91d7069c37093141f28dfff6f2638d83619c9.php(46): craft\helpers\Template::attribute()
#21 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(407): __TwigTemplate_b47380db31655379a8b0cdfe334aa911492e0c187d161727e0afdc6241cd40d5->doDisplay()
#22 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#23 /home/forge/gencon-admin-staging.thesmithy.io/storage/runtime/compiled_templates/28/2851cc18371d758520b9ff7409f12d5f213d177888fef2dedaea73a352a3cc2b.php(256): Twig\Template->display()
#24 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(184): __TwigTemplate_fff343e811f9eaf700b726ae793257712b657bf8511e6669e4e013dcf4d66ad4->block_content()
#25 /home/forge/gencon-admin-staging.thesmithy.io/storage/runtime/compiled_templates/d3/d30b37d5bce4a9890c9a3bc342f473d64c86829b03acf88419fbae77b6b2401f.php(495): Twig\Template->displayBlock()
#26 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(184): __TwigTemplate_bb1a6a45c783c069ae550547b5e9e3dc17741e3634724dcbe48159014c3a2398->block_main()
#27 /home/forge/gencon-admin-staging.thesmithy.io/storage/runtime/compiled_templates/d3/d30b37d5bce4a9890c9a3bc342f473d64c86829b03acf88419fbae77b6b2401f.php(314): Twig\Template->displayBlock()
#28 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(184): __TwigTemplate_bb1a6a45c783c069ae550547b5e9e3dc17741e3634724dcbe48159014c3a2398->block_body()
#29 /home/forge/gencon-admin-staging.thesmithy.io/storage/runtime/compiled_templates/3c/3cdecfb6dbd97b83f21073b86ca311b948a831637d28aff194571197670c142d.php(85): Twig\Template->displayBlock()
#30 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(407): __TwigTemplate_af79730261256377791c451283349fc625258aaed45c86c63bb252a607a8dcb1->doDisplay()
#31 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#32 /home/forge/gencon-admin-staging.thesmithy.io/storage/runtime/compiled_templates/62/62e3f15a8f7f52daabac0dbe93c59b335d41a876cc01a730d704f406f130aa47.php(56): Twig\Template->display()
#33 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(407): __TwigTemplate_1f22f13855591b8c4dc819d5c91c3c8dc2ee9e37bdeb81e0b5fb69a460c811ef->doDisplay()
#34 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#35 /home/forge/gencon-admin-staging.thesmithy.io/storage/runtime/compiled_templates/d3/d30b37d5bce4a9890c9a3bc342f473d64c86829b03acf88419fbae77b6b2401f.php(156): Twig\Template->display()
#36 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(407): __TwigTemplate_bb1a6a45c783c069ae550547b5e9e3dc17741e3634724dcbe48159014c3a2398->doDisplay()
#37 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#38 /home/forge/gencon-admin-staging.thesmithy.io/storage/runtime/compiled_templates/28/2851cc18371d758520b9ff7409f12d5f213d177888fef2dedaea73a352a3cc2b.php(114): Twig\Template->display()
#39 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(407): __TwigTemplate_fff343e811f9eaf700b726ae793257712b657bf8511e6669e4e013dcf4d66ad4->doDisplay()
#40 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#41 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Template.php(392): Twig\Template->display()
#42 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#43 /home/forge/gencon-admin-staging.thesmithy.io/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#44 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render()
#45 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/View.php(450): craft\web\View->renderTemplate()
#46 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/Controller.php(241): craft\web\View->renderPageTemplate()
#47 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/controllers/FieldsController.php(260): craft\web\Controller->renderTemplate()
#48 [internal function]: craft\controllers\FieldsController->actionEditField()
#49 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#50 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#51 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#52 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#53 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#54 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#55 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest()
#56 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#57 /home/forge/gencon-admin-staging.thesmithy.io/web/index.php(22): yii\base\Application->run()
#58 {main}
```

Its happening in the Super Table settings twig but not sure if this is on the CMS or Plugin side that is causing the error when `field.hasErrors()` is called.

```
{% set field = layoutElement.getField() %}
                            
                            <div class="supertableconfigitem stci-field{% if field.hasErrors() %} error{% endif %} {% if loop.first %}sel{% endif %}" data-id="{{ fieldId }}">
```

**Comment by mcclaskiem** [comment]
Confirmed that removing this `{% if field.hasErrors() %}`, allows the settings menu to load when trying to access a field with super table in it. In my case, it is inside of a matrix block.

FWIW: This error does not occur locally for me and I am running the same version of PHP on both my server and locally. The only difference between the two is MySQL but the error seems to go away when altering the twig template that is installed on the server.

**Comment by jsellerIPOP** [comment]
Did you manage to find a resolution to this error as I have experienced a similar issue when trying to edit a Matrix field with Super table under Setting > Fields

Current version:
`craftcms/cms": "3.5.17.1"
verbb/super-table": "2.6.5",`

![Screenshot 2021-01-13 at 11 51 20](https://user-images.githubusercontent.com/11872932/104449381-6dc4c700-5596-11eb-9749-5a92984df43c.png)

Thanks

**Comment by olivierbon** [comment]
Just had the same issue cropping up in Support and clearing the content of `storage/runtime` flushed the problem (though running Utilities → Clear caches or `./craft clear-caches/all` should do it too).

**Comment by engram-design** [comment]
From the error message with @mcclaskiem and @olivierbon feedback, this looks like a template case issue. Please comment if this is still an issue after clearing those.
