### ISSUE TITLE
Undefined property: verbb\supertable\elements\db\SuperTableBlockQuery::$pageItems

### ISSUE THREAD

**Issue by clarknelson** [engram-design/SuperTable#398]
**Description**

When I save my entry with a new / removed block, I see this error.

![image](https://user-images.githubusercontent.com/4106671/102364991-b465d800-3f7c-11eb-8b75-5d15932c1575.png)

in `storage/logs/web.log`
```
2020-12-16 06:56:12 [-][1][mhdjmhtk4n32srgl9ij8kr4mh5][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined property: verbb\supertable\elements\db\SuperTableBlockQuery::$pages in /home/forge/default/vendor/yiisoft/yii2/base/ArrayableTrait.php:126
Stack trace:
#0 /home/forge/default/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError()
#1 /home/forge/default/vendor/yiisoft/yii2/base/ArrayableTrait.php(126): craft\web\ErrorHandler->handleError()
#2 /home/forge/default/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1638): craft\elements\db\ElementQuery->toArray()
#3 /home/forge/default/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1591): craft\elements\db\ElementQuery->getCriteria()
#4 /home/forge/default/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1502): craft\elements\db\ElementQuery->getCachedResult()
#5 /home/forge/default/vendor/verbb/super-table/src/elements/db/SuperTableBlockQuery.php(110): craft\elements\db\ElementQuery->one()
#6 /home/forge/default/vendor/yiisoft/yii2/base/ArrayableTrait.php(126): verbb\supertable\elements\db\SuperTableBlockQuery->__get()
#7 /home/forge/default/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1638): craft\elements\db\ElementQuery->toArray()
#8 /home/forge/default/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1611): craft\elements\db\ElementQuery->getCriteria()
#9 /home/forge/default/vendor/verbb/super-table/src/fields/SuperTableField.php(541): craft\elements\db\ElementQuery->setCachedResult()
#10 /home/forge/default/vendor/craftcms/cms/src/base/Element.php(3345): verbb\supertable\fields\SuperTableField->normalizeValue()
#11 /home/forge/default/vendor/craftcms/cms/src/base/Element.php(2788): craft\base\Element->normalizeFieldValue()
#12 /home/forge/default/vendor/craftcms/cms/src/controllers/EntriesController.php(744): craft\base\Element->setFieldValuesFromRequest()
#13 /home/forge/default/vendor/craftcms/cms/src/controllers/EntriesController.php(355): craft\controllers\EntriesController->_populateEntryModel()
#14 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#15 /home/forge/default/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#16 /home/forge/default/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#17 /home/forge/default/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#18 /home/forge/default/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#19 /home/forge/default/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#20 /home/forge/default/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction()
#21 /home/forge/default/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest()
#22 /home/forge/default/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#23 /home/forge/default/web/index.php(21): yii\base\Application->run()
#24 {main}
```

**Steps to reproduce**
1. Saving the entry without changing the blocks does not throw an error
2. Adding a new block or removing an existing block creates this error
3. This does not happen on my local development environment, just on the live server.

**Additional info**
- Plugin version: 2.6.4
- Craft version: 3.5.17
- Multi-site: No

**Additional context**

My server is running MySql v8 do you think this is the issue?

**Comment by engram-design** [comment]
Refer to https://github.com/verbb/super-table/issues/397
