### ISSUE TITLE
Invalid owner ID: 27777

### ISSUE THREAD

**Issue by janlonden** [engram-design/SuperTable#417]
**Description**

We're getting `Invalid owner ID: 27777` when disabling a Super Table field and then trying to publish a draft.

```
2021-06-29 11:01:03 [-][1][232747992d92f1c1df351a1533a42b4c][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 27777 in /var/www/html/vendor/verbb/super-table/src/elements/SuperTableBlockElement.php:303
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/ElementHelper.php(380): verbb\supertable\elements\SuperTableBlockElement->getOwner()
#1 /var/www/html/vendor/craftcms/cms/src/helpers/ElementHelper.php(394): craft\helpers\ElementHelper::rootElement(Object(verbb\supertable\elements\SuperTableBlockElement))
#2 /var/www/html/vendor/mmikkel/cache-flag/src/CacheFlag.php(234): craft\helpers\ElementHelper::isDraftOrRevision(Object(verbb\supertable\elements\SuperTableBlockElement))
#3 /var/www/html/vendor/mmikkel/cache-flag/src/CacheFlag.php(188): mmikkel\cacheflag\CacheFlag->_maybeInvalidateFlaggedCachesByElement(Object(verbb\supertable\elements\SuperTableBlockElement))
#4 [internal function]: mmikkel\cacheflag\CacheFlag->mmikkel\cacheflag\{closure}(Object(craft\events\DeleteElementEvent))
#5 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\DeleteElementEvent))
#6 /var/www/html/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('craft\\services\\...', 'beforeDeleteEle...', Object(craft\events\DeleteElementEvent))
#7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1498): yii\base\Component->trigger('beforeDeleteEle...', Object(craft\events\DeleteElementEvent))
#8 /var/www/html/vendor/verbb/super-table/src/fields/SuperTableField.php(1076): craft\services\Elements->deleteElement(Object(verbb\supertable\elements\SuperTableBlockElement), false)
#9 /var/www/html/vendor/craftcms/cms/src/base/Element.php(3377): verbb\supertable\fields\SuperTableField->beforeElementDelete(Object(benf\neo\elements\Block))
#10 /var/www/html/vendor/spicyweb/craft-neo/src/elements/Block.php(492): craft\base\Element->beforeDelete()
#11 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1502): benf\neo\elements\Block->beforeDelete()
#12 /var/www/html/vendor/spicyweb/craft-neo/src/services/Fields.php(580): craft\services\Elements->deleteElement(Object(benf\neo\elements\Block))
#13 /var/www/html/vendor/spicyweb/craft-neo/src/services/Fields.php(547): benf\neo\services\Fields->_deleteNeoBlocksAndStructures(Object(benf\neo\Field), Object(craft\elements\Entry), Array)
#14 /var/www/html/vendor/spicyweb/craft-neo/src/services/Fields.php(374): benf\neo\services\Fields->_deleteOtherBlocks(Object(benf\neo\Field), Object(craft\elements\Entry), Array)
#15 /var/www/html/vendor/spicyweb/craft-neo/src/Field.php(669): benf\neo\services\Fields->duplicateBlocks(Object(benf\neo\Field), Object(craft\elements\Entry), Object(craft\elements\Entry), true)
#16 /var/www/html/vendor/craftcms/cms/src/base/Element.php(3359): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), false)
#17 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1581): craft\base\Element->afterPropagate(false)
#18 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1162): craft\elements\Entry->afterPropagate(false)
#19 /var/www/html/vendor/craftcms/cms/src/services/Drafts.php(442): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#20 /var/www/html/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(441): craft\services\Drafts->publishDraft(Object(craft\elements\Entry))
#21 [internal function]: craft\controllers\EntryRevisionsController->actionPublishDraft()
#22 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#24 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('publish-draft', Array)
#25 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('publish-draft', Array)
#26 /var/www/html/vendor/craftcms/cms/src/web/Application.php(278): yii\base\Module->runAction('entry-revisions...', Array)
#27 /var/www/html/vendor/craftcms/cms/src/web/Application.php(581): craft\web\Application->runAction('entry-revisions...', Array)
#28 /var/www/html/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#29 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 /var/www/html/web/index.php(24): yii\base\Application->run()
#31 {main}
```

**Additional info**
- Plugin version: 2.6.8
- Craft version: 3.6.17
- Multi-site: Yes

**Comment by brokenhd** [comment]
Same issue I am running into as well, when updating an old entry I get this error.

**Comment by murphy1484** [comment]
Same error here when trying to publish a draft.

**Comment by Saboteur777** [comment]
Same error when trying to revert to a previous revision of an entry.

**Comment by tigerchick** [comment]
Just came across the same thing as @Saboteur777 using Craft 4.7.3 and Supertable 3.0.12
I ran the "Check Content Tables" tool - it found some issues (I have just updated from Craft 3)
I ran the "re-save fields" tool - it fixed the issues.
I then tried reverting my entry again to a previous version and still get the error:
"Invalid Configuration – [yii\base\InvalidConfigException](https://www.yiiframework.com/doc-2.0/yii-base-invalidconfigexception.html)
Invalid owner ID: xxxx"

**Comment by tigerchick** [comment]
> Just came across the same thing as @Saboteur777 using Craft 4.7.3 and Supertable 3.0.12 I ran the "Check Content Tables" tool - it found some issues (I have just updated from Craft 3) I ran the "re-save fields" tool - it fixed the issues. I then tried reverting my entry again to a previous version and still get the error: "Invalid Configuration – [yii\base\InvalidConfigException](https://www.yiiframework.com/doc-2.0/yii-base-invalidconfigexception.html) Invalid owner ID: xxxx"

My issue seems to be related to the Gold Site Copy plugin:  https://github.com/Goldinteractive/craft-sitecopy
I disabled that and all working fine again.
