### ISSUE TITLE
Check Content Table utility causing error after upgrade

### ISSUE THREAD

**Issue by bliswebagency** [engram-design/SuperTable#542]
### Describe the bug

Hello, while trying to run the 'Check Content Table' utility we are receiving the error below

```
TypeError: craft\helpers\ProjectConfig::unpackAssociativeArrays(): Argument #1 ($array) must be of type array, null given, called in /myapp/vendor/verbb/super-table/src/controllers/PluginController.php on line 426 and defined in /myapp/vendor/craftcms/cms/src/helpers/ProjectConfig.php:331
Stack trace:
#0 /myapp/vendor/verbb/super-table/src/controllers/PluginController.php(426): craft\helpers\ProjectConfig::unpackAssociativeArrays(NULL)
#1 [internal function]: verbb\supertable\controllers\PluginController->actionCheckContentTables()
#2 /myapp/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /myapp/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#4 /myapp/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('check-content-t...', Array)
#5 /myapp/vendor/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction('super-table/plu...', Array)
#6 /myapp/vendor/craftcms/cms/src/web/Application.php(608): craft\web\Application->runAction('super-table/plu...', Array)
#7 /myapp/vendor/craftcms/cms/src/web/Application.php(274): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /myapp/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /myapp/web/index.php(41): yii\base\Application->run()
#10 {main}
```

### Steps to reproduce

1. Press the 'Check Content Table' button in the Super-table plugin settings page
2. Receive error message above

### Craft CMS version

3.9.6

### Plugin version

2.7.5.1

### Multi-site?

Yes

### Additional context

We have a content builder configuration with matrix children inside super tables.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/super-table:"dev-craft-3 as 2.7.5.1"`.
