### ISSUE TITLE
Craft 5 Upgrade Error

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [engram-design/SuperTable#560]
### Describe the bug

I'm attempting to upgrade to Craft 5 but hit this error:

```
Exception 'craft\errors\DeprecationException' with message 'The `accordion` static Super Table field is no longer supported. Update any references from `block.myField` to `block.one().myField`.'
```

Here's the full stack trace:

```
Exception 'craft\errors\DeprecationException' with message 'The `accordion` static Super Table field is no longer supported. Update any references from `block.myField` to `block.one().myField`.'

in /var/www/html/cms/vendor/yiisoft/yii2/base/Component.php:180

Stack trace:
#0 /var/www/html/cms/vendor/verbb/super-table/src/fields/SuperTableField.php(59): craft\services\Deprecator->log('verbb\\supertabl...', 'The `accordion`...')
#1 /var/www/html/cms/vendor/yiisoft/yii2/base/Component.php(180): verbb\supertable\fields\SuperTableField->setStaticField(NULL)
#2 /var/www/html/cms/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('staticField', NULL)
#3 /var/www/html/cms/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(verbb\supertable\fields\SuperTableField), Array)
#4 /var/www/html/cms/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#5 /var/www/html/cms/vendor/craftcms/cms/src/base/Field.php(271): craft\base\Model->__construct(Array)
#6 /var/www/html/cms/vendor/craftcms/cms/src/fields/Matrix.php(307): craft\base\Field->__construct(Array)
#7 /var/www/html/cms/vendor/verbb/super-table/src/fields/SuperTableField.php(54): craft\fields\Matrix->__construct(Array)
#8 [internal function]: verbb\supertable\fields\SuperTableField->__construct(Array)
#9 /var/www/html/cms/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#10 /var/www/html/cms/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('verbb\\supertabl...', Array, Array)
#11 /var/www/html/cms/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('verbb\\supertabl...', Array, Array)
#12 /var/www/html/cms/vendor/craftcms/cms/src/Craft.php(70): yii\BaseYii::createObject(Array, Array)
#13 /var/www/html/cms/vendor/craftcms/cms/src/helpers/Component.php(142): Craft::createObject(Array)
#14 /var/www/html/cms/vendor/craftcms/cms/src/services/Fields.php(372): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#15 /var/www/html/cms/vendor/craftcms/cms/src/services/Fields.php(399): craft\services\Fields->createField(Array)
#16 [internal function]: craft\services\Fields->craft\services\{closure}(Array, 4)
#17 /var/www/html/cms/vendor/craftcms/cms/src/base/MemoizableArray.php(90): call_user_func(Object(Closure), Array, 4)
#18 /var/www/html/cms/vendor/craftcms/cms/src/base/MemoizableArray.php(76): craft\base\MemoizableArray->normalizeByKey(4)
#19 [internal function]: craft\base\MemoizableArray->craft\base\{closure}(4)
#20 /var/www/html/cms/vendor/craftcms/cms/src/base/MemoizableArray.php(76): array_map(Object(Closure), Array)
#21 /var/www/html/cms/vendor/craftcms/cms/src/base/MemoizableArray.php(104): craft\base\MemoizableArray->normalize(Array)
#22 /var/www/html/cms/vendor/craftcms/cms/src/services/Fields.php(423): craft\base\MemoizableArray->all()
#23 /var/www/html/cms/vendor/craftcms/cms/src/Craft.php(367): craft\services\Fields->getAllFields(false)
#24 /var/www/html/cms/vendor/craftcms/cms/src/Craft.php(242): Craft::_fields()
#25 /var/www/html/cms/vendor/craftcms/cms/src/Craft.php(205): Craft::_autoloadCustomFieldBehavior()
#26 [internal function]: Craft::autoload('craft\\behaviors...')
#27 /var/www/html/cms/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct('craft\\behaviors...')
#28 /var/www/html/cms/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies('craft\\behaviors...')
#29 /var/www/html/cms/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\behaviors...', Array, Array)
#30 /var/www/html/cms/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\behaviors...', Array, Array)
#31 /var/www/html/cms/vendor/yiisoft/yii2/base/Component.php(756): yii\BaseYii::createObject(Array)
#32 /var/www/html/cms/vendor/yiisoft/yii2/base/Component.php(740): yii\base\Component->attachBehaviorInternal('customFields', Array)
#33 /var/www/html/cms/vendor/yiisoft/yii2/base/Component.php(465): yii\base\Component->ensureBehaviors()
#34 /var/www/html/cms/vendor/craftcms/cms/src/db/Query.php(51): yii\base\Component->hasEventHandlers('init')
#35 /var/www/html/cms/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\db\Query->init()
#36 /var/www/html/cms/vendor/craftcms/cms/src/elements/db/ElementQuery.php(575): yii\base\BaseObject->__construct(Array)
#37 /var/www/html/cms/vendor/craftcms/cms/src/elements/GlobalSet.php(139): craft\elements\db\ElementQuery->__construct('craft\\elements\\...')
#38 /var/www/html/cms/vendor/craftcms/cms/src/services/Globals.php(556): craft\elements\GlobalSet::find()
#39 /var/www/html/cms/vendor/craftcms/cms/src/services/Globals.php(262): craft\services\Globals->_allSets(1)
#40 /var/www/html/cms/config/colour-swatches.php(27): craft\services\Globals->getSetByHandle('design')
#41 /var/www/html/cms/vendor/craftcms/cms/src/services/Config.php(289): include('/var/www/html/c...')
#42 /var/www/html/cms/vendor/craftcms/cms/src/services/Config.php(281): craft\services\Config->_configFromFileInternal('/var/www/html/c...')
#43 /var/www/html/cms/vendor/craftcms/cms/src/services/Plugins.php(933): craft\services\Config->getConfigFromFile('colour-swatches')
#44 /var/www/html/cms/vendor/craftcms/cms/src/services/Plugins.php(233): craft\services\Plugins->createPlugin('colour-swatches', Array)
#45 /var/www/html/cms/vendor/craftcms/cms/src/base/ApplicationTrait.php(1640): craft\services\Plugins->loadPlugins()
#46 /var/www/html/cms/vendor/craftcms/cms/src/console/Application.php(53): craft\console\Application->_postInit()
#47 /var/www/html/cms/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#48 /var/www/html/cms/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#49 /var/www/html/cms/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#50 [internal function]: yii\console\Application->__construct(Array)
#51 /var/www/html/cms/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#52 /var/www/html/cms/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\console\\A...', Array, Array)
#53 /var/www/html/cms/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#54 /var/www/html/cms/vendor/craftcms/cms/src/Craft.php(70): yii\BaseYii::createObject(Array, Array)
#55 /var/www/html/cms/vendor/craftcms/cms/bootstrap/bootstrap.php(316): Craft::createObject(Array)
#56 /var/www/html/cms/vendor/craftcms/cms/bootstrap/console.php(42): require('/var/www/html/c...')
#57 /var/www/html/cms/craft(12): require('/var/www/html/c...')
#58 {main}
````

I could send you the db, composer.json and composer.lock if you wanted to take a look as I'm assuming that nobody else has this issue.

i'm not sure where to go from here; it's weird because a month or so ago i ran a upgrade test and i was able to upgrade  but now i'm getting that weird issue.

Thanks again as always 🎉

### Steps to reproduce

1. upgrade to 5
2. See error in terminal

### Craft CMS version

5.1.8

### Plugin version

4

### Multi-site?

no

**Comment by engram-design** [comment]
So the deprecation notice is normal during the upgrade, but it shouldn't be a fatal error unless you have something like the [`throwExceptions`](https://craftcms.com/knowledge-base/preparing-for-craft-4#fix-deprecation-warnings) enabled?

**Comment by DynamiteGoesBoom** [comment]
@engram-design is it fatal with these settings in `config/app.php` too?: 

```'
deprecator' => [
            'throwExceptions' => App::env('DEV_MODE'),
        ],
````

Thanks as always!

**Comment by DynamiteGoesBoom** [comment]
@engram-design yeah it looks like that setting was messing with upgrade process. However, there's one final ST Migration that fails to run:

```
Checking for pending Craft and plugin migrations ...
Total 1 new Super Table migration to be applied:
    - m240115_000000_craft5

Total 1 new Wishlist migration to be applied:
    - m231229_000000_content_refactor

Apply the above migrations? (yes|no) [no]:y
Create database backup? (yes|no) [no]:
Skipping database backup.
*** applying m240115_000000_craft5
    > update in {{%elements}} ... done (time: 0.031s)
    > update in {{%changedfields}} ... done (time: 0.005s)
    > delete from {{%stc_17_style}} ... done (time: 0.000s)
    > update in {{%elements}} ... done (time: 0.023s)
    > update in {{%changedfields}} ... done (time: 0.004s)
    > delete from {{%stc_5_slides}} ... done (time: 0.000s)
    > update in {{%elements}} ... done (time: 0.023s)
    > update in {{%changedfields}} ... done (time: 0.004s)
    > delete from {{%stc_19_style}} ... done (time: 0.000s)
    > update in {{%elements}} ... done (time: 0.023s)
    > update in {{%changedfields}} ... done (time: 0.004s)
    > delete from {{%stc_11_promotions}} ... done (time: 0.000s)
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.elementId' in 'on clause'
The SQL being executed was: SELECT COUNT(*)
FROM `elements_sites` `es`
INNER JOIN `stc_62_style` `c` ON `c`.`elementId` = `es`.`elementId` and `c`.`siteId` = `es`.`siteId`
INNER JOIN `elements` `e` ON `e`.`id` = `es`.`elementId`
WHERE `es`.`elementId` IN (SELECT `id`
FROM `supertableblocks`
WHERE `typeId`=94) (/var/www/html/cms/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/cms/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'SELECT COUNT(*)...')
#1 /var/www/html/cms/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT COUNT(*)...')
#2 /var/www/html/cms/vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /var/www/html/cms/vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /var/www/html/cms/vendor/yiisoft/yii2/db/Query.php(368): yii\db\Query->queryScalar('COUNT(*)', NULL)
#5 /var/www/html/cms/vendor/craftcms/cms/src/migrations/BaseContentRefactorMigration.php(106): yii\db\Query->count()
#6 /var/www/html/cms/vendor/verbb/super-table/src/migrations/m240115_000000_craft5.php(80): craft\migrations\BaseContentRefactorMigration->updateElements(Object(craft\db\Query), Object(craft\models\FieldLayout), '{{%stc_62_style...', 'field_')
#7 /var/www/html/cms/vendor/craftcms/cms/src/db/Migration.php(49): verbb\supertable\migrations\m240115_000000_craft5->safeUp()
#8 /var/www/html/cms/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#9 /var/www/html/cms/vendor/craftcms/cms/src/console/controllers/MigrateController.php(382): yii\console\controllers\BaseMigrateController->migrateUp('m240115_000000_...')
#10 [internal function]: craft\console\controllers\MigrateController->actionAll()
#11 /var/www/html/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/cms/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#14 /var/www/html/cms/vendor/craftcms/cms/src/console/controllers/MigrateController.php(195): yii\console\Controller->runAction('all', Array)
#15 /var/www/html/cms/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#16 /var/www/html/cms/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#17 /var/www/html/cms/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#18 /var/www/html/cms/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#19 /var/www/html/cms/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run('migrate/all', Array)
#20 /var/www/html/cms/vendor/craftcms/cms/src/console/controllers/UpController.php(60): craft\console\Controller->run('migrate/all', Array)
#21 [internal function]: craft\console\controllers\UpController->actionIndex()
#22 /var/www/html/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /var/www/html/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#24 /var/www/html/cms/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#25 /var/www/html/cms/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('', Array)
#26 /var/www/html/cms/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('', Array)
#27 /var/www/html/cms/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#28 /var/www/html/cms/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#29 /var/www/html/cms/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('up', Array)
#30 /var/www/html/cms/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#31 /var/www/html/cms/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#32 /var/www/html/cms/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#33 /var/www/html/cms/craft(13): yii\base\Application->run()
#34 {main}
*** failed to apply m240115_000000_craft5 (time: 0.136s)
```

Any ideas on what could be causing that? I also had an issue with Snipcart migrations too. But I uninstalled that for now so I could just focus on getting through the ST migrations.

FWIW `stc_62_style` is empty.

**Comment by DynamiteGoesBoom** [comment]
i'm starting to realize why some of my ST data gets mixed up at times:

![Screenshot 2024-06-06 at 5 20 16 PM](https://github.com/verbb/super-table/assets/39201467/3e4ced8f-148a-4751-9898-c73dd313b7cf)

For whatever reason the referenced table changes periodically. Which ends up with strange results. I had a good long convo with Tommy at P&T about it too.

I've been working on setting up the Element API endpoints so that I can basically get all of our Fido sites running on fresh installs, then just import the data back in.

I think this will be the best course of action as we need to get away from MariaDB anyway. So might as well kill 2 birds with one stone.

Thanks for all of your help 🎉

**Comment by jamie-jenks** [comment]
> @engram-design is it fatal with these settings in `config/app.php` too?:
> 
> ```
> deprecator' => [
>             'throwExceptions' => App::env('DEV_MODE'),
>         ],
> ```
> 
> Thanks as always!

This saved me! Thank you 🙏
