### ISSUE TITLE
Issue when migrating from craft 3 to 4

### ISSUE THREAD

**Issue by yalamber** [engram-design/SuperTable#565]
### Describe the bug

I am having issue updating from craft 3 to 4 and it seems like it's during super table migration it's failing
Below is the error i receive. I already updated to latest craft 3 version and also all plugins. 
```
*** applying m220511_054742_delete_converted_field_block_types_and_groups
Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.supertableblocks_owners' doesn't exist
The SQL being executed was: SELECT `elements`.`id`, `elements`.`canonicalId`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateLastMerged`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`id` AS `siteSettingsId`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `supertableblocks`.`fieldId`, `supertableblocks`.`primaryOwnerId`, `supertableblocks`.`typeId`, `supertableblocks_owners`.`ownerId`, `supertableblocks_owners`.`sortOrder`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`
FROM `elements` `elements`
INNER JOIN `supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `elements`.`id`
INNER JOIN `supertableblocks_owners` `supertableblocks_owners` ON (`supertableblocks_owners`.`blockId` = `elements`.`id`) AND (`supertableblocks_owners`.`ownerId` = `supertableblocks`.`primaryOwnerId`)
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
WHERE (`supertableblocks`.`primaryOwnerId`=426) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)
ORDER BY `supertableblocks_owners`.`sortOrder`) `subquery`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `supertableblocks` `supertableblocks` ON `supertableblocks`.`id` = `subquery`.`elementsId`
INNER JOIN `supertableblocks_owners` `supertableblocks_owners` ON (`supertableblocks_owners`.`blockId` = `elements`.`id`) AND (`supertableblocks_owners`.`ownerId` = `supertableblocks`.`primaryOwnerId`)
ORDER BY `supertableblocks_owners`.`sortOrder` (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'SELECT `element...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute('SELECT `element...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(417): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(252): yii\db\Query->all(NULL)
#5 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1649): craft\db\Query->all(NULL)
#6 /var/www/html/vendor/verbb/super-table/src/fields/SuperTableField.php(1167): craft\elements\db\ElementQuery->all()
#7 /var/www/html/vendor/craftcms/cms/src/base/Element.php(5205): verbb\supertable\fields\SuperTableField->beforeElementDelete(Object(benf\neo\elements\Block))
#8 /var/www/html/vendor/spicyweb/craft-neo/src/elements/Block.php(666): craft\base\Element->beforeDelete()
#9 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2120): benf\neo\elements\Block->beforeDelete()
#10 /var/www/html/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(652): craft\services\Elements->deleteElement(Object(benf\neo\elements\Block))
#11 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1159): benf\neo\services\BlockTypes->handleDeletedBlockType(Object(craft\events\ConfigEvent))
#12 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#13 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func(Array, Object(craft\events\ConfigEvent))
#14 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#15 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(530): craft\models\ProjectConfigData->commitChanges(Array, NULL, 'neoBlockTypes.2...', true, NULL, true)
#16 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(490): craft\services\ProjectConfig->_setInternal('neoBlockTypes.2...', NULL, NULL, true, false)
#17 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(547): craft\services\ProjectConfig->set('neoBlockTypes.2...', NULL, NULL)
#18 /var/www/html/vendor/spicyweb/craft-neo/src/migrations/m220511_054742_delete_converted_field_block_types_and_groups.php(40): craft\services\ProjectConfig->remove('neoBlockTypes.2...')
#19 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(50): benf\neo\migrations\m220511_054742_delete_converted_field_block_types_and_groups->safeUp()
#20 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#21 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(361): yii\console\controllers\BaseMigrateController->migrateUp('m220511_054742_...')
#22 [internal function]: craft\console\controllers\MigrateController->actionAll()
#23 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#25 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#26 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('all', Array)
#27 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#28 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#29 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#30 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#31 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#32 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#33 /var/www/html/craft(27): yii\base\Application->run()
#34 {main}
*** failed to apply m220511_054742_delete_converted_field_block_types_and_groups (time: 0.050s)
```

### Steps to reproduce

1. Upgrade to latest craft 3 version and also compatible plugins
2. composer update for craft 4 and all plugins
3. Run php craft migrate/all

### Craft CMS version

4

### Plugin version

3.0.14

### Multi-site?

no

**Comment by engram-design** [comment]
Hmm, looks to be related to Neo re-saving blocks before Super Table has had time to apply it's migrations (one of which is to add `supertableblocks_owners` as a database table). I might suggest disabling either Neo or Super Table and run the migrations to upgrade, then re-enable them.

**Comment by yalamber** [comment]
yea so what i did was first migrate super table migrations with 
php craft migrate/up --plugin=super-table
then ran php craft migrate/all      
all migration was successful then
