### ISSUE TITLE
Craft 5 Initial Migrations Fail: The `item` static Super Table field is no longer supported. Update any references from `block.myField` to `block.one().myField`

### ISSUE THREAD

**Issue by NathanBate** [engram-design/SuperTable#566]
### Describe the bug

When I run the initial Craft 5 migrations, they fail. I have a Craft Matrix field with a Super Table block in it. When [this craft migration](https://github.com/craftcms/cms/blob/7e14327a84130f67f067e46a290405498acc52dc/src/migrations/m230511_000000_field_layout_configs.php#L25) is triggered, it fails on line 25 because of this Matrix --> Super Table Block.

Full Error stack:
```
*** applying m230511_000000_field_layout_configs
Exception: The `item` static Super Table field is no longer supported. Update any references from `block.myField` to `block.one().myField`. (/var/www/html/vendor/yiisoft/yii2/base/Component.php:180)
#0 /var/www/html/vendor/verbb/super-table/src/fields/SuperTableField.php(59): craft\services\Deprecator->log('verbb\\supertabl...', 'The `item` stat...')
#1 /var/www/html/vendor/yiisoft/yii2/base/Component.php(180): verbb\supertable\fields\SuperTableField->setStaticField(NULL)
#2 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('staticField', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(verbb\supertable\fields\SuperTableField), Array)
#4 /var/www/html/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#5 /var/www/html/vendor/craftcms/cms/src/base/Field.php(271): craft\base\Model->__construct(Array)
#6 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(307): craft\base\Field->__construct(Array)
#7 /var/www/html/vendor/verbb/super-table/src/fields/SuperTableField.php(54): craft\fields\Matrix->__construct(Array)
#8 [internal function]: verbb\supertable\fields\SuperTableField->__construct(Array)
#9 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#10 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('verbb\\supertabl...', Array, Array)
#11 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('verbb\\supertabl...', Array, Array)
#12 /var/www/html/vendor/craftcms/cms/src/Craft.php(70): yii\BaseYii::createObject(Array, Array)
#13 /var/www/html/vendor/craftcms/cms/src/helpers/Component.php(142): Craft::createObject(Array)
#14 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(352): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#15 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(379): craft\services\Fields->createField(Array)
#16 [internal function]: craft\services\Fields->craft\services\{closure}(Array, 113)
#17 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(90): call_user_func(Object(Closure), Array, 113)
#18 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(171): craft\base\MemoizableArray->normalizeByKey(113)
#19 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(477): craft\base\MemoizableArray->firstWhere('uid', '570b25db-fabd-4...', true)
#20 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(183): craft\services\Fields->getFieldByUid('570b25db-fabd-4...')
#21 /var/www/html/vendor/yiisoft/yii2/base/Component.php(180): craft\fieldlayoutelements\CustomField->setFieldUid('570b25db-fabd-4...')
#22 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('fieldUid', '570b25db-fabd-4...')
#23 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\fieldlayoutelements\CustomField), Array)
#24 /var/www/html/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#25 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(73): craft\base\Model->__construct(Array)
#26 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(47): craft\fieldlayoutelements\BaseField->__construct(Array)
#27 [internal function]: craft\fieldlayoutelements\CustomField->__construct(NULL, Array)
#28 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#29 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\fieldlayo...', Array, Array)
#30 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\fieldlayo...', Array, Array)
#31 /var/www/html/vendor/craftcms/cms/src/Craft.php(70): yii\BaseYii::createObject(Array, Array)
#32 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(1013): Craft::createObject(Array)
#33 /var/www/html/vendor/craftcms/cms/src/models/FieldLayoutTab.php(264): craft\services\Fields->createLayoutElement(Array)
#34 /var/www/html/vendor/yiisoft/yii2/base/Component.php(180): craft\models\FieldLayoutTab->setElements(Array)
#35 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('elements', Array)
#36 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\models\FieldLayoutTab), Array)
#37 /var/www/html/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#38 /var/www/html/vendor/craftcms/cms/src/models/FieldLayoutTab.php(123): craft\base\Model->__construct(Array)
#39 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(903): craft\models\FieldLayoutTab->__construct(Array)
#40 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(829): craft\services\Fields->_legacyTabsByLayoutId(Object(craft\models\FieldLayout))
#41 [internal function]: craft\services\Fields->craft\services\{closure}(Array, 22)
#42 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(90): call_user_func(Object(Closure), Array, 22)
#43 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(76): craft\base\MemoizableArray->normalizeByKey(22)
#44 [internal function]: craft\base\MemoizableArray->craft\base\{closure}(22)
#45 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(76): array_map(Object(Closure), Array)
#46 /var/www/html/vendor/craftcms/cms/src/base/MemoizableArray.php(104): craft\base\MemoizableArray->normalize(Array)
#47 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(917): craft\base\MemoizableArray->all()
#48 /var/www/html/vendor/craftcms/cms/src/migrations/m230511_000000_field_layout_configs.php(25): craft\services\Fields->getAllLayouts()
#49 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\m230511_000000_field_layout_configs->safeUp()
#50 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#51 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(365): yii\console\controllers\BaseMigrateController->migrateUp('m230511_000000_...')
#52 [internal function]: craft\console\controllers\MigrateController->actionAll()
#53 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#54 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#55 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#56 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('all', Array)
#57 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#58 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#59 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#60 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#61 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#62 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#63 /var/www/html/craft(13): yii\base\Application->run()
#64 {main}
```

### Steps to reproduce

1. Update composer dependancies to Craft 5 compatible
2. Run composer update
3. Run craft migrations and it fails on the field_layout_configs migration.

### Craft CMS version

5.0.0 and 5.3

### Plugin version

4.0.0 and 4.0.2

### Multi-site?

No

**Comment by NathanBate** [comment]
Found the solution here on [this issue](https://github.com/verbb/super-table/issues/560). Turning off the deprecator fixes it.
